src/objects/Activity_Outcomes__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipLabel>Activity Outcomes</relationshipLabel>
        <relationshipName>Activity_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Outcome</label>
    <nameField>
        <label>Allowable Outcomes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Activity_Type__c.object
<CustomObject>
    <description>Contains Activity Types and attributes</description>
    <label>Activity Type</label>
    <nameField>
        <label>Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UI Task Code</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SRActivitiesEditExtensionTest.cls
@IsTest
public class SRActivitiesEditExtensionTest {

    public static testmethod void testConstrutor(){
            
            TestHelper.createData();  
            
            
            Activity_Type__c t= new Activity_Type__c(Name='BULKUPDA');
            insert t;
            
            Activity_Outcomes__c outcome= new Activity_Outcomes__c(Name='Test',Activity_Type__c=t.id);
            insert  outcome;
            
            Test.startTest();
                    Case c = TestHelper.caseRrd;
                    
                    OUC_Activity__c activity = [Select Id FROM OUC_Activity__c WHERE Case__c=:c.Id LIMIT 1];
                    activity.activity_type__c = t.id;
                    
                    update activity;
                                    
                    ApexPages.standardController ct= new  ApexPages.standardController(activity);
                    SRActivitiesEditExtension ext = new SRActivitiesEditExtension(ct);
                    
            Test.stopTest();
            
    }

}