src/objects/Activity_Type__c.object
<CustomObject>
    <description>Contains Activity Types and attributes</description>
    <label>Activity Type</label>
    <nameField>
        <label>Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UI Task Code</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Code__c</fullName>
        <label>Open311 Task Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OUCActivitybeforeinsert_Test.cls
@isTest 
public class OUCActivitybeforeinsert_Test{

static testMethod void testMethod1(){
    
    TestHelper.createData();
    
    Case c = [Select Id From Case Limit 1];
    
    OUC_Activity__c obj1 = new OUC_Activity__c ();
    obj1.Task_Code__c ='ABC';
    obj1.Case__c = c.Id;
    insert obj1;
    
    OUC_Activity__c obj2 = new OUC_Activity__c ();
    obj2.Task_Code__c ='REINSPEC';
    obj2.Case__c = c.Id;
    insert obj2;
    
    Activity_Type__c  activityObj = new Activity_Type__c(Name='REINSPEC');
    insert activityObj;
    Activity_Type__c  activityObj2 = new Activity_Type__c(Name='DEFAULT');
    insert activityObj2;
    
     OUC_Activity__c obj3 = new OUC_Activity__c ();
     obj3.Activity_Type__c =activityObj.Id;
     obj3.Case__c = c.Id;
     insert obj3;
     
     OUC_Activity__c obj4 = new OUC_Activity__c ();
     obj4.Task_Code__c ='ABC';
     obj4.Case__c = c.Id;
     obj3.Activity_Type__c =activityObj2.Id;
     insert obj4;
     
     OUC_Activity__c obj5 = new OUC_Activity__c ();
     obj5.Activity_Type__c =activityObj.Id;
     obj5.Case__c = c.Id;
     obj5.Task_Code__c ='REINSPEC';
     insert obj5;
}
}