src/objects/Activity_Type__c.object
<CustomObject>
    <description>Contains Activity Types and attributes</description>
    <label>Activity Type</label>
    <nameField>
        <label>Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <formula>SRType__r.Jurisdiction__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Dept Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Status__c</fullName>
        <formula>Text(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SR Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicing_Agency__c</fullName>
        <formula>SRType__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicing Agency</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Jurisdiction__c.object
<CustomObject>
    <description>Stores Agency and Department Information of DC Government.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <description>This Field contains DC Government Agency Abbreviations like -  DDOT, DPW</description>
        <label>Servicing Agency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Agency Dept Code</label>
    <nameField>
        <label>Agency Dept Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Dept Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UI Task Code</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Task_Code__c</fullName>
        <formula>blankvalue(Activity_Type__r.Name, Task_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Task_Short_Name__c</fullName>
        <formula>BLANKVALUE(Activity_Type__r.Task_Short_Name__c,Task_Short_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Short Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SR_Status__c</fullName>
        <formula>Text(Case__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SR Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>Jurisdiction__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on legacy CSR, this field defines the Agency and sub-department at that agency responsible for servicing this SR Type.</description>
        <label>Agency Dept Code</label>
        <referenceTo>Jurisdiction__c</referenceTo>
        <relationshipLabel>Service Request Types</relationshipLabel>
        <relationshipName>Service_Request_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgencySRActivityCodesCtrl.cls
public class AgencySRActivityCodesCtrl {

  private final Integer TYPE_AGENCY = 0;
  private final Integer TYPE_SR = 1;

  public String activeServicingAgency { get; set; }
  public String selectedType { get; set; }

  public List<SelectOption> agencyPicklistOptions;
  public List<SelectOption> serviceReportTypes;
  public List<OUC_Activity__c> activitiesBySRType;

  public AgencySRActivityCodesCtrl() {
    
  }

  public List<SelectOption> getAgencyPicklistOptions() {
    if (agencyPicklistOptions == null) {
      agencyPicklistOptions = new List<SelectOption> ();
      agencyPicklistOptions.add(new SelectOption('', '-- Select an Agency --'));
      // Get all the servicing agencies. 
      List<Jurisdiction__c> types = [Select Id, Name, Agency__c From Jurisdiction__c];
      Set<String> srTypes = new Set<String> ();
      // Loop through the results and set the select options for the picklist.
      for (Jurisdiction__c srtype : types) {
        if (!srTypes.contains(srType.Agency__c) && srtype.Agency__c != null) {
          srTypes.add(srType.Agency__c);
          agencyPicklistOptions.add(new SelectOption(srtype.Agency__c, srtype.Agency__c));
        }
      }
      System.debug('');
    }
    return agencyPicklistOptions;
  }

  public List<SelectOption> getServiceRequestTypesForAgency() {
    serviceReportTypes.add(new SelectOption('', '-- Select a Service Request Type --'));
    List<AggregateResult> results;
    // Get all the SRType's for activeServicingAgency cases to add to the picklist.
    results = [Select SRType__r.Id, SRType__r.Service_Name__c From Case Where Servicing_Agency__c = :activeServicingAgency Group By SRType__r.Service_Name__c, SRType__r.Id];
    // Loop through the results and set the select options for the picklist.
    for (AggregateResult ar : results) {
      serviceReportTypes.add(new SelectOption((String) ar.get('Id'), (String) ar.get('Service_Name__c')));
    }
    return serviceReportTypes;
  }

  public List<OUC_Activity__c> getActivitysBySRType() {
    List<Case> lastClosedSRForType = [Select Id, SRType__c From Case Where SR_Status__c = 'Closed' AND Servicing_Agency__c = :activeServicingAgency AND SRType__c = :selectedType ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 1];
    System.debug('----> Query: Select Id, SRType__r.Service_Name__c From Case Where SR_Status__c = \'Closed\' AND Servicing_Agency__c = '+activeServicingAgency+' AND SRType__c = '+selectedType+' ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 1');
    System.debug('----> lastClosedSRForType: ' + lastClosedSRForType);

    if (lastClosedSRForType != null && lastClosedSRForType.size() == 1) {
      activitiesBySRType = [Select Id, Final_Task_Code__c, Final_Task_Short_Name__c	, Phone__c, Priority__c, Subject__c, Activity_Type__c From OUC_Activity__c Where Case__c = :lastClosedSRForType.get(0).Id];
    }
    System.debug('----> activitiesBySRType: ' + activitiesBySRType);
    return activitiesBySRType;
  }

  public PageReference picklistChanged() {
    // TODO: Add switch for Agency vs Type
    serviceReportTypes = new List<SelectOption>();
    activitiesBySRType = new List<OUC_Activity__c>();
    String actionType = ApexPages.currentPage().getParameters().get('actionType');

    try {
      Integer type = Integer.valueOf(actionType);

      if (type == TYPE_AGENCY) {
        selectedType = '';
      } else if (type == TYPE_SR) {

      }
    } catch (TypeException e) {
      System.debug('----> TypeException: The given string cannot be converted to an Integer');
    }
    return null;
  }
}