src/objects/Activity_Outcomes__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipLabel>Activity Outcomes</relationshipLabel>
        <relationshipName>Activity_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Outcome</label>
    <nameField>
        <label>Allowable Outcomes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Activity_Type__c.object
<CustomObject>
    <description>Contains Activity Types and attributes</description>
    <label>Activity Type</label>
    <nameField>
        <label>Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UI Task Code</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SRActivitiesEditExtension.cls
public with sharing class SRActivitiesEditExtension{
    
    public List<SelectOption> outComeValues {get;set;}
    public Case service_request {get;set;}
    public ApexPages.StandardController controller {get;set;}
    
    public SRActivitiesEditExtension(ApexPages.StandardController controller) {
      this.controller = controller;
      outComeValues  = new List<SelectOption>();
        
      OUC_Activity__c activity = [Select Activity_Type__c,Case__c FROM OUC_Activity__c WHERE Id=:controller.getId()];
       
      if(activity.Case__c != null) {
        service_request = ServiceRequestsHelper.getRequest(activity.Case__c);                                                                 
      }
        
      List<Activity_Outcomes__c> outcomes= [Select Id,Name FROM Activity_Outcomes__c WHERE Activity_Type__c =:activity.Activity_Type__c];
      if(outcomes.size()>0){
        for(Activity_Outcomes__c ao:outcomes)
          outComeValues.add(new SelectOption(ao.Id,ao.Name));
      }                    
    }
    
    public PageReference save() {        
        // Save the new changes.
        try{
        	
		    if(this.controller.save() != null){
		      // Send user back to SR Activity details page.
		      PageReference newPage = New PageReference('/' + ApexPages.currentPage().getParameters().get('id'));
		      newPage.setRedirect(true);
		      return newPage;
		    }
		    return null;

		  } catch (DMLException ex) {
		     ApexPages.addMessages(ex);
		     return null;
		  }
    }
}