src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FlexNotes__c</fullName>
        <label>FlexNotes (not used)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>Answer_Date_Time__c</fullName>
        <label>Answer Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Email_CaseBulkDateController.cls
public class Email_CaseBulkDateController {

  public String caseId { get; set; }

  public Email_CaseBulkDateController() {
    
  }

  public String getBulkScheduleDate() {
    System.debug('----> Case Id: ' + caseId);
    System.debug('----> Page Param: ' + ApexPages.currentPage().getParameters().get('parentId'));
    List<Case> caseToFetchFlexnotes = [Select Id, CaseNumber, (Select Id, Questions__c, Order__c, FlexNote_Question__c, Answer_Date_Time__c, Answer__c From FlexNotes__r) From Case Where Id = :caseId];

    if (caseToFetchFlexnotes != null && caseToFetchFlexnotes.size() == 1) {
      System.debug('----> caseToFetchFlexnotes: ' + caseToFetchFlexnotes);
      for (FlexNote__c fNote : caseToFetchFlexnotes.get(0).FlexNotes__r) {
        System.debug('----> Fnote: ' + fNote);
        if (fNote.Questions__c.containsIgnoreCase('BULK COLLECTION DATE')) {
          return fNote.Answer__c;
        }
      }
    }
    return '';
  }
}