src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>DuplicateDetectionMethod__c</fullName>
        <description>Specifies duplicate detection algorithm and/or process to be implemented for this SR type.</description>
        <label>Duplicate Detection Method</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DuplicateRadius__c</fullName>
        <description>Required when Standard duplicate detection method selected.  The is a parameter specified in feet for another SR to be considered a potential duplicate.  Enter 1 to create an effective exact address match.</description>
        <inlineHelpText>in feet</inlineHelpText>
        <label>Duplicate Radius (feet)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duplicate_Threshold_Period__c</fullName>
        <description>An optional parameter for duplicate detection method Standard.  This specifies the number of days prior to today for an SR to be considered a potential duplicate.</description>
        <inlineHelpText>in days</inlineHelpText>
        <label>Duplicate Threshold Period (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceRequestsHelperTest.cls
@isTest
public class ServiceRequestsHelperTest {
  
  public static testMethod void testHandleDuplicateClosures() {
    TestHelper.createData();
        
    List<Case> parentCaseList = [Select Id, ContactId, SRType__c From Case Where Status = 'Open' Limit 1];
    List<ServiceRequestType__c> srTypeList = [Select Id From ServiceRequestType__c Where Name = 'DMV19' Limit 1];
        
    if (parentCaseList.size() == 1 && srTypeList.size() == 1) {
      Case parentCase = parentCaseList.get(0); 
      ServiceRequestType__c srType = srTypeList.get(0);  
        
      srType.DuplicateDetectionMethod__c = 'Standard';
      srType.DuplicateRadius__c = 1;
      srType.Duplicate_Threshold_Period__c = 55;
        
      parentCase.GeoLocation__Latitude__s = 38.933;
      parentCase.GeoLocation__Longitude__s = -76.963;
            
      Case dupCase1 = new Case(
        ParentId = parentCase.Id,
        Status = 'Duplicate (Opened)',
        SRType__c = srType.Id,
        ContactId = parentCase.ContactId,
        GeoLocation__Latitude__s = 38.933,
        GeoLocation__Longitude__s = -76.963
      );
        
       Case dupCase2 = new Case(
        ParentId = parentCase.Id,
        Status = 'Duplicate (Opened)',
        SRType__c = srType.Id,
        ContactId = parentCase.ContactId,
        GeoLocation__Latitude__s = 38.933,
        GeoLocation__Longitude__s = -76.963
      );
      
      Test.startTest();  
      update srType;
         
      List<Case> tempCaseList = new List<Case>();
      tempCaseList.add(parentCase);
      tempCaseList.add(dupCase1);
      tempCaseList.add(dupCase2);
      upsert tempCaseList;
      
      // Manually update the case to closed to trigger a duplicate check.
      parentCase.Status = 'Closed';
      update parentCase;
        
      Test.stopTest();
    }
  }
}