src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Ward</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUCServiceRequestConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is the custom setting stores parameters</description>
    <fields>
        <fullName>BulkCollectionScheduleQuestion__c</fullName>
        <description>This is for testing purpose</description>
        <label>Bulk Collection Schedule Question</label>
        <type>TextArea</type>
    </fields>
    <label>OUC ServiceRequest Config</label>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batchClassBulkCollectionTest.cls
@isTest(seealldata=true)
private class batchClassBulkCollectionTest {
     static testMethod void start() {
     
        batchClassBulkCollection  bc=new batchClassBulkCollection ();
        Database.BatchableContext BatchCont;
        
        contact con=new contact();
        con.lastname='jois';
        con.email='jois@gmail.com';
        insert con;                      
        
        OUCServiceRequestConfig__c OSR=[SELECT BulkCollectionScheduleQuestion__c FROM OUCServiceRequestConfig__c];
        string str=OSR.BulkCollectionScheduleQuestion__c;
        string ido;
        list<FlexNoteQuestion__c> FF=[SELECT id,Questions__c FROM FlexNoteQuestion__c ];
        for(integer i=0;i<FF.size();i++){
              if(FF[i].Questions__c.contains(str))
                  ido=FF[i].id;   
        }
        
        list<ServiceRequestType__c> SRT=[Select Id FROM ServiceRequestType__c WHERE Service_Name__c='Bulk Collection'];
               
        list<case> cas=new list<case>();
        case c=new case();
        c.ContactId=con.id;
        c.Ward__c='Ward 2';
        c.Origin='311-App';
        c.SRType__c=SRT[0].Id;           //'a06r000000048nzAAA';
        insert c;
        cas.add(c);              
        
        FlexNoteQuestion__c FNQ=new FlexNoteQuestion__c();
        FNQ.Questions__c='NEXT BULK SCHEDULE COLLECTION DATE';
        FNQ.Object_Name__c='case';
        FNQ.Name='E0710';
        FNQ.Answer_Type__c='text';
        insert FNQ;
        
        FlexNote__c FN=new FlexNote__c();
        //FN.Name='a02r0000000UyEi';
        FN.FlexNote_Question__c=ido;       //'a01r0000000Bu49AAC';
        FN.Case__c=c.id;
        FN.Answer__c='';
        insert FN;           
        
        SelfSchedule schedBatch= new SelfSchedule(); 
        String chron = '0 0 12 * * ?';        
        system.schedule('Test Sched', chron, schedBatch);     
        
        bc.start(BatchCont);
        bc.execute(BatchCont,cas);
        bc.finish(BatchCont);
    }
}