src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Servicing_Agency__c</fullName>
        <formula>SRType__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicing Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE( Status, 
&quot;Closed&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed - Incomplete Information&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Closed)&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Opened)&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;In Progress&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Voided&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Dispute&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Open&quot;, &quot;/img/samples/flag_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;Status Flag&quot;)

&amp; &apos; &apos; &amp; TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Open311_API_Log__c.object
<CustomObject>
    <fields>
        <fullName>APIKey__c</fullName>
        <label>Api Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Method__c</fullName>
        <label>Request Method</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Param__c</fullName>
        <label>Request Param</label>
        <length>131071</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Format__c</fullName>
        <label>Response Format</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Open311 API Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open311 API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Open311ApiKeyConfig__c.object
<CustomObject>
    <fields>
        <fullName>ApiKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Api Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Request_Date__c</fullName>
        <description>The last date and time a request was made using this key to the api.</description>
        <label>Last Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of requests allocated to the API Key used.</description>
        <label>30 Day Usage Limit Allocation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Reset_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the the usage limit will be reset.</description>
        <inlineHelpText>Set this to the date you wish to have the api key&apos;s usage be reset. The application will automatically register the next iteration 30 days from the date specified when a call is made on the reset date.</inlineHelpText>
        <label>Last Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Used__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of usage limit that has been used already.</description>
        <label>30 Day Usage Limit Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Open 311 Api Key Config</label>
    <nameField>
        <label>Agency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open 311 Api Key Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>Jurisdiction__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Name__c</fullName>
        <description>If populated, this is the service name displayed on the citizen portal.</description>
        <label>External Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Open311APIHelper.cls
public with sharing class Open311APIHelper {

  /*
    some utility methods to be used across open311 helper
   */
  /**
    @brief Convert an ISO 8601 timestamp to an Apex \c DateTime value.
   
    Uses the JSONParser getDateTimeValue() method.
   
    See http://en.wikipedia.org/wiki/ISO_8601 for timestamp format details.
   
    Throws a System.JSONException if \p iso8601_ts is not a valid ISO 8601
    timestamp.
   
    @param iso8601_ts Valid ISO 8601 timestamp.
   
    @return a \c DateTime value for the given timestamp
   */
  public static DateTime convertTimestamp(String iso8601_ts)
  {
    // Create a valid JSON string like '{"t":"2012-07-31T11:22:33.444Z"}'
    JSONParser parser = JSON.createParser('{"t":"' + iso8601_ts + '"}');

    parser.nextToken(); // advance to the start object marker
    parser.nextValue(); // advance to the next value

    // Bug in JSONParser or DateTime object results in a malformed DateTime,
    // so convert to Long and back to DateTime.  Without the conversion,
    // methods that access timeGmt() and its components will actually get
    // local time instead of GMT.
    return DateTime.newInstance(parser.getDateTimeValue().getTime());

    // Once bug is fixed, this return is preferred.
    // return parser.getDateTimeValue();
  }

  /*
    @Purpose:-
    validate api key
   
    contains the logic for validation api key and updating response in case
    of error
   
    returns true if everything is fine / false in error
   */
  public static APIValidations.APIKeyResponse checkAPIKey(String apiKey, RestRequest req, RestResponse response, String format) {
    if (apiKey == null || apiKey == '') {
      //invalid apikey provided:-
      response.statuscode = 400;
      String responseStr = req.headers.get('Content-Type') == APIConstants.CONTENT_TYPE_JSON || format == 'json' ?
      CustomException.sendJSONApiErrorResponse(' api_key not  provided') :
      CustomException.sendXMLApiErrorResponse('api_key not  provided');
      response.responseBody = Blob.valueOf(responseStr);

      return null;
    }

    APIValidations.APIKeyResponse apiKeyRes = APIValidations.validateKey(apiKey);
    System.debug('----> [Open311-Test] apiKeyRes: ' + apiKeyRes);	
    if (apiKeyRes.isValid == false) {
      //we have an invalid api key provided
      response.statuscode = 400;
      String responseStr = req.headers.get('Content-Type') == APIConstants.CONTENT_TYPE_JSON || format == 'json' ?
      CustomException.sendJSONApiErrorResponse(' Invalid api_key  provided') :
      CustomException.sendXMLApiErrorResponse(' Invalid api_key  provided');
      response.responseBody = Blob.valueOf(responseStr);

      logRequest(req, 'Error', 'Invalid api_key provided');

      return null;
    }

    //System.debug('----> [Open311-Test] Open311APIHelper => apiKeyRes.usageLimitUsed >= apiKeyRes.usageLimit: ' + (apiKeyRes.usageLimitUsed >= apiKeyRes.usageLimit));
    //System.debug('----> [Open311-Test] Open311APIHelper => apiKeyRes.usageLimitResetDate == null: ' + (apiKeyRes.usageLimitResetDate == null));
    //System.debug('----> [Open311-Test] Open311APIHelper => (apiKeyRes.usageLimitResetDate.year() == Date.today().year() && apiKeyRes.usageLimitResetDate.month() == Date.today().month()): ' + ((apiKeyRes.usageLimitResetDate.year() == Date.today().year() && apiKeyRes.usageLimitResetDate.month() == Date.today().month())));

    // Verify the api usage limit access. 
    // IF: 
    // 1. Used calls is GREATER THAN OR EQUAL TO Limit amount.
    // 2. Reset date is blank not allowing for a bypass OR the last time a reset occured was this month and year.
    if (apiKeyRes.usageLimitUsed >= apiKeyRes.usageLimit && (apiKeyRes.usageLimitResetDate == null || (apiKeyRes.usageLimitResetDate.year() == Date.today().year() && apiKeyRes.usageLimitResetDate.month() == Date.today().month()))) {
      response.statuscode = 400;
      String responseStr = req.headers.get('Content-Type') == APIConstants.CONTENT_TYPE_JSON || format == 'json' ?
      CustomException.sendJSONApiErrorResponse(' Usage limit exceeded for this API User.') :
      CustomException.sendXMLApiErrorResponse(' Usage limit exceeded for this API User.');
      response.responseBody = Blob.valueOf(responseStr);
      logRequest(req, 'Error', 'Usage limit exceeded for this API User.');

      return null;
    }
    return apiKeyRes;
  }

  /*
    @Purpose:-
    Create log records	       	            
   */
  public static void logRequest(RestRequest req, String status, String message) {
    /*
      create a log object
     */
    Open311_API_Log__c log = new Open311_API_Log__c();
    log.Log__c = message;
    log.status__c = status;
    log.apikey__c = req.params.get('api_key');
    log.Endpoint__c = req.requestURI;
    log.response_format__c = req.requestURI.split('\\.').size() > 1 ? req.requestURI.split('\\.') [1] : 'xml';
    log.Request_Method__c = req.httpMethod;
    log.Request_Param__c = JSON.serialize(req.params);
    insert log;

    // Build a mapping of strings for the logging params.
    Map<String, String> logParams = new Map<String, String> ();
    logParams.put('Status', status);
    logParams.put('API_Key', req.params.get('api_key'));
    logParams.put('Endpoint', req.requestURI);
    logParams.put('Response_Format', req.requestURI.split('\\.').size() > 1 ? req.requestURI.split('\\.') [1] : 'xml');
    logParams.put('Request_Method', req.httpMethod);
    logParams.putAll(req.params);

    // Get the API Name based on the Key.
    try {
      Open311ApiKeyConfig__c keyConfig = [Select Name From Open311ApiKeyConfig__c Where ApiKey__c = :req.params.get('api_key')];
      logParams.put('API_Name', keyConfig.Name);
    } catch(Exception e) {
      System.debug('----> Unable to fetch name for API Key');
    }

    try {
      String srId = '';
      /*
        // Get the Service Request ID from the message.
        List<String> messageSplit = message.split(':');
       
        if (messageSplit.size() == 2) {
        srId = messageSplit.get(1);
        srId = srId.replaceAll(' ', '');
        // Query for the case object.
        List<Case> request = [Select Id, Servicing_Agency__c, SRType__r.Name From Case Where Id = :srId]; 
        // Get fields required.
        if (request != null && request.size() == 1) {
        logParams.put('Request_Type', request.get(0).SRType__r.Name);
        logParams.put('Agency', request.get(0).Servicing_Agency__c);
        }
        }*/

      List<ServiceRequestType__c> srType = [Select Id, Name, Agency__c, Service_Name__c, External_Name__c From ServiceRequestType__c Where Name = :req.params.get('service_code')];

      if (srType != null && srType.size() == 1) {
        logParams.put('service_type', (srType.get(0).External_Name__c == null ? srType.get(0).Service_Name__c : srType.get(0).External_Name__c));
        logParams.put('agency', srType.get(0).Agency__c);
      }
    } catch(Exception e) {
      System.debug('----> Unable to get Service Request Type using given code.');
    }
    // Send the log.
    Incapsulate_Log.Loggly.singleLog(message, DateTime.now(), 'VERBOSE', logParams);
  }

  /**
   * logAPIUsage
   *
   * @description This function will increment the API keys usage in the OUC system.
   * @author Darkis
   * @param key The string representation of the API key provided by the requesting user.
   */
  public static void logAPIUsage(String key) {
    try {
      // Grab the key config for the given key.
      List<Open311ApiKeyConfig__c> keyConfig = [Select Id, Usage_Limit_Used__c, Usage_Limit_Allocation__c, Last_Request_Date__c From Open311ApiKeyConfig__c Where ApiKey__c = :key LIMIT 1];
      // If the config is available.
      if (keyConfig != null && keyConfig.size() == 1) {
        // Increment the key's usage. 
        keyConfig.get(0).Usage_Limit_Used__c = keyConfig.get(0).Usage_Limit_Used__c != null ? keyConfig.get(0).Usage_Limit_Used__c + 1 : 1;
        keyConfig.get(0).Last_Request_Date__c = Datetime.now();
        update keyConfig;
      }
    } catch(DMLException e) {
      System.debug('----> Unable to increment key usage.');
    }
  }

  public static void resetUsageLimit(String apikey) {
    try {
    List<Open311ApiKeyConfig__c> keyConfig = [Select Id, Name, ApiKey__c, Usage_Limit_Allocation__c, Usage_Limit_Used__c, Usage_Limit_Reset_Date__c FROM Open311ApiKeyConfig__c WHERE ApiKey__c = :apikey];

    if (keyConfig != null && keyConfig.size() == 1) {
      keyConfig[0].Usage_Limit_Used__c = 0;
      keyConfig[0].Usage_Limit_Reset_Date__c = Date.today();
      upsert keyConfig;
    }
    } catch (DMLException e) { 
      System.debug('----> Unable to reset usage limit for API apikey');
    }
  }

}