src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Closure_Comment__c</fullName>
        <label>Case Closure Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseAfterUpdateTest.cls
@isTest
public class CaseAfterUpdateTest {
  public static testMethod void testTrigger() {
    Test.startTest();
    TestHelper.createData();

    List<Contact> con = [Select Id From Contact Limit 1];
    List<ServiceRequestType__c> srType = [Select Id From ServiceRequestType__c Limit 1];

    if (con != null && con.size() == 1 && srType != null && srType.size() == 1) {
      Case c = new Case
      (
       Origin = 'Phone',
       Status = 'Open',
       ContactId = con[0].Id,
       SRType__c = srType[0].Id
      );
      insert c;

      Case c2 = new Case
      (
       Origin = 'Phone',
       Status = 'Duplicate (Opened)',
       ContactId = con[0].Id,
       SRType__c = srType[0].Id,
       ParentId = c.Id
      );
      insert c2;

      c2.Status = 'Voided';
      c2.Case_Closure_Comment__c = 'Closing Duplicate Case. This should close the primary.';
      c2.Reason = '1- Closed, issue resolved';
      upsert c2;

      Test.stopTest();

      Case updatedC = [Select Id, Status, Case_Closure_Comment__c, Reason From Case Where Id = :c.Id];
      System.assertEquals('Voided', updatedC.Status);
    }
  }
}