src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Console311Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is for console search functionality.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Console 311 Settings</label>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>ContactRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not used - replaced by Contact Status picklist</description>
        <label>Contact Required (not used)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Method__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Method</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>311-App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Priority__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Status__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Required field - will always be set to Case.</description>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SR_Alert_Message__c</fullName>
        <description>Text entered displays at top of Agent Console when SR Type is selected.</description>
        <label>SR Alert Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceLocationRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Location Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Console311_SearchControllerTest.cls
@isTest
public class Console311_SearchControllerTest{
    
    public static testMethod void testController(){
        
        PageReference pageRef = Page.Console311_Search;
        Test.setCurrentPage(pageRef);
        Contact con=[SELECT Id FROM Contact LIMIT 1];
        Case caseRec=[SELECT Id FROM Case LIMIT 1]; 
        
        List<Id> fixedSearchResults= new List<Id>();
        fixedSearchResults.add(caseRec.Id);
        fixedSearchResults.add(con.id);
        Test.setFixedSearchResults(fixedSearchResults);
        
        Console311_SearchController controller=new Console311_SearchController();
        
        // Verify that object list is two
        System.assertEquals(2, controller.getObjectList().size());
        
        //Search for a word
        controller.searchString='Park';
        controller.doSearch();
        
        // Verify that map size is two
        System.assertEquals(2, controller.serachResults.size());
        
        //Assert case is size 1
        System.assertEquals(1, controller.serachResults.get('Case').size);
        
        //Assert contact is size 1
        System.assertEquals(1, controller.serachResults.get('Contact').size);
        
    }
    
    @testSetup static void createTestData() {
        
        //Create Contact
        Contact contact = New Contact(FirstName='Parker',LastName='Last', email='test@test.com',Phone='111111');
        insert contact;
        
        //Create Case
        ServiceRequestType__c serviceRequest=new ServiceRequestType__c(Name='Parking',Object__c='Case',Service_Name__c='Parking Meter Issue',Default_Status__c='New',Default_Priority__c='Standard',Default_Method__c='Phone',ContactRequired__c=true,ServiceLocationRequired__c=true,SR_Alert_Message__c='Test Message');
        insert serviceRequest;        
        
        Case caseRecord=new Case(Origin='Phone',subject='Parking Meter Repair',Status='New',ContactId=contact.Id,SRType__c=serviceRequest.Id);
        insert caseRecord;
        
        //Insert Custom Settings
        List<Console311Settings__c> csList=new List<Console311Settings__c>();
        
        Console311Settings__c cs = new Console311Settings__c();
        cs.name = 'ObjectsToSearch';
        cs.Value__c = 'Case;Contact';
        csList.add(cs);
        
        Console311Settings__c cs1 = new Console311Settings__c();
        cs1.name = 'FieldSetName';
        cs1.Value__c = 'DCConsoleSearchFieldset';
        csList.add(cs1);
        
        Console311Settings__c cs2 = new Console311Settings__c();
        cs2.name = 'Limit';
        cs2.Value__c = '25';
        csList.add(cs2);
        
        insert csList; 
        
    }
    
    
    
}