src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ANC__c</fullName>
        <label>ANC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressID__c</fullName>
        <description>MAR Address_Id</description>
        <label>Address ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Resolution_Date__c</fullName>
        <formula>/*IF( 
   ISPICKVAL(SRType__r.SLAType__c, &apos;Calendar days&apos;) ,
   CreatedDate+VALUE(BLANKVALUE(SRType__r.SLA__c,SRType_Jurisdiction__r.SLA__c)),  
   IF(ISPICKVAL(SRType__r.SLAType__c, &apos;Business days&apos;),          CreatedDate+VALUE(BLANKVALUE(SRType__r.SLA__c,SRType_Jurisdiction__r.SLA__c))+
		( VALUE(BLANKVALUE(SRType__r.SLA__c,SRType_Jurisdiction__r.SLA__c)) - Business_Days_Count__c)
		, null
	) 
)

*/

IF(
ISPICKVAL(SRType__r.SLAType__c, &apos;Calendar days&apos;) ,
CreatedDate+VALUE(BLANKVALUE(SLA__c,SRType__r.SLA__c)),
IF(ISPICKVAL(SRType__r.SLAType__c, &apos;Business days&apos;), ExpectedBusinessResolutionDate__c
, null
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Resolution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System_Name__c</fullName>
        <label>External System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntersectionId__c</fullName>
        <label>Intersection Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Amharic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vietnamese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Media_URL__c</fullName>
        <label>Media URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PSA__c</fullName>
        <label>PSA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quadrant__c</fullName>
        <label>Quadrant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMD__c</fullName>
        <label>SMD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicing_Agency__c</fullName>
        <formula>SRType__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicing Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE( Status, 
&quot;Closed&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed - Incomplete Information&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Closed)&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Opened)&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;In Progress&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Voided&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Dispute&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Open&quot;, &quot;/img/samples/flag_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;Status Flag&quot;)

&amp; &apos; &apos; &amp; TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Ward</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XCOORD__c</fullName>
        <label>XCOORD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Flex_Note_History__c.object
<CustomObject>
    <fields>
        <fullName>Service_Request_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request History</label>
        <referenceTo>Service_Request_History__c</referenceTo>
        <relationshipLabel>Flex Note Histories</relationshipLabel>
        <relationshipName>Flex_Note_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flex Note History</label>
    <nameField>
        <label>Flex Note History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flex Note Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity_History__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Internal Comments (deprecated)</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request History</label>
        <referenceTo>Service_Request_History__c</referenceTo>
        <relationshipName>OUC_Activity_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity History</label>
    <nameField>
        <label>OUC Activity HIstory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Activity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request_History__c.object
<CustomObject>
    <fields>
        <fullName>ANC__c</fullName>
        <label>ANC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressID__c</fullName>
        <label>Address ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>Case Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactFirstName__c</fullName>
        <description>Contact first name mapped to this field</description>
        <label>Contact FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactLastName__c</fullName>
        <description>Contact Last name mapped to this field</description>
        <label>Contact LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactPhone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <label>Date/Time Opened (deprecated)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateTimeClosed__c</fullName>
        <label>Date/Time Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DateTimeOpened__c</fullName>
        <label>Date/Time Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Resolution_Date__c</fullName>
        <label>Expected Resolution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System_Name__c</fullName>
        <label>External_System_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntersectionId__c</fullName>
        <label>Intersection Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Amharic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vietnamese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Othe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LastUpdateDateTime__c</fullName>
        <label>LastUpdateDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Media_URL__c</fullName>
        <label>Media URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Neighbor_Hood_Cluster__c</fullName>
        <label>Neighbor Hood Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Case Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>311-App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA__c</fullName>
        <label>PSA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Dispute</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quadrant__c</fullName>
        <label>Quadrant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMD__c</fullName>
        <label>SMD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servicing_Agency__c</fullName>
        <label>Servicing Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Incomplete Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Closed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Opened)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Ward</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XCOORD__c</fullName>
        <label>XCOORD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request History</label>
    <nameField>
        <label>Service Request History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceRequestHistoryHelper.cls
public with sharing class ServiceRequestHistoryHelper {
     /**
       * Queries for the specified request by service request id(case id) and returns the corresponding
       * response object.
       *
       * @param id  request's id
       * @return    A response version of the matching request.
       *            If no records are found, it will simply error message saying invalid/not found
       */
       public static Service_Request_History__c getRequest(String requestId){
            
            string query=buildGetQueryRoot();
            query+='WHERE Name=\'' +requestId +'\' ';

            List<Service_Request_History__c> cases = database.query(query);
                               
            if(cases.size()==0){
                 //invalid requestId code provided data could not be found
                  throw new CustomException(APIConstants.NOT_FOUND); 
            }
            return cases[0];
            
       }
       
       
        private static String buildGetQueryRoot(){
            string query = 'Select name, casenumber__c, IsClosed__c, status__c,description__c,Subject__c,Servicing_Agency__c,';
            query+='CreatedDate__c,LastModifiedDate,DateTimeOpened__c,LastUpdateDateTime__c,';
            query+='DateTimeClosed__c, Address__c,AddressID__c,geolocation__latitude__s,';
            query+='geolocation__longitude__s,media_url__c,Expected_Resolution_Date__c,ContactFirstName__c,Contactlastname__c,';
            query+='ContactPhone__c,Contact_Email__c,Priority__c,Origin__c,Device__c,SLA__c,External_Id__c,External_System_Name__c,Language__c,';
            query+='IntersectionId__c,Quadrant__c,Ward__c,District__c,PSA__c,ANC__c,SMD__c,Neighbor_Hood_Cluster__c,XCOORD__c,YCOORD__c,Zipcode__c,';
            query+='Jurisdiction_Code__c,IsClosedOnCreate__c,Reason__c,Service_Type_Code__c,';
            query+='Jurisdiction_Description__c,SRType__c,Deleted__c,';
            query+='(Select  name,questions__c,Order__c, Answer__c, ';
            query+=' CodeDescription__c, FlexNote_Question__c, IsSecure__c FROM Flex_Note_Histories__r ORDER BY Order__c, ID  ),';
            query+='(Select Id,Status__c,Task_Code__c,Task_Short_Name__c,Citizen_Email_On_Complete__c,';
            query+='Description__c,external_comments__c,outcome__c,Display_Sort_order__c,completion_date__c,';
            query+='Due_Date__c,Responsible_Party__c FROM OUC_Activity_Histories__r ORDER BY Display_Sort_Order__c )';
            query+='FROM Service_Request_History__c ';
            
            return query;
            
        }
       
        
     
       /**
       * Queries for list of Requests records and and returns the corresponding
       * response object (list of Requests).  If any non-null parameters are
       * provided, the list will be filtered by the specified field.
       *
       * @param jurisdiction_id    Id of jurisdiction
       * @return              Collection of Requests objects, as an list
       */
        public static List<Service_Request_History__c> listAllRequests(String filter,Boolean isPrivate){
           
            string query=buildGetQueryRoot();
            
            //adding filter
            if(filter==null){
                query +=' WHERE DateTimeOpened__c >= LAST_90_DAYS ';
            }
            else {
                query +=' WHERE '+filter;
            }
            // do not return deleted SR's to the public  (only private API key holders)
            if(!isPrivate){
                query+=' AND Deleted__c=false';
            }
            
            
            String limitBy = isPrivate ?' 400':' 1000';
            String orderBy = isPrivate ?' LastUpdateDateTime__c ASC, Name ASC, CaseNumber__c ASC': 'DateTimeOpened__c DESC';
            
            query +=' ORDER BY '+orderBy+' LIMIT '+limitBy;

            system.debug('FILTER:' + filter);
            System.debug(query);
            return database.query(query);
            
        } 
        
        public static void updateCaseAsDeleted(List<String> caseNumbers){
            List<Service_Request_History__c> cases = [Select Id,Deleted__c from Service_Request_History__c WHERE Name IN:caseNumbers];
            List<Id> SRHIds = new List<Id>();
            for(Service_Request_History__c c:cases){
                c.deleted__c=true;
                SRHIds.add(c.Id);
            }
            update cases;
            // Now get the linked FlexNote Historys that are not already marked as deleted
            //    flex notes are master detail, so before delete doesn't fire if Case (master) is deleted
            List<Flex_Note_History__c> FNHs = [SELECT Id,Deleted__c From Flex_Note_History__c WHERE Service_Request_History__c IN:SRHIds AND Deleted__c=false];
            for(Flex_Note_History__c fh:FNHs){
                fh.deleted__c=true;
            }
            update FNHs;
        }
        public static void updateFlexNoteHistoryAsDeleted(List<String> FlexNoteIds){
            List<Flex_Note_History__c> FNHs = [Select Id,Deleted__c from Flex_Note_History__c WHERE Flex_Note_Id__c IN:FlexNoteIds];
            for(Flex_Note_History__c c:FNHs){
                c.deleted__c=true;
            }
            update FNHs;
        }
        public static void updateOUCActivityHistoryAsDeleted(List<String> ActivityIds){
            List<OUC_Activity_History__c> AHs = [Select Id,Deleted__c from OUC_Activity_History__c WHERE Activity_Id__c IN:ActivityIds];
            for(OUC_Activity_History__c c:AHs){
                c.deleted__c=true;
            }
            update AHs;
        }
}