src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlexNotes__c</fullName>
        <label>FlexNotes (not used)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CreateCaseEventsTest.cls
@isTest 
private class  CreateCaseEventsTest{ 
    static testmethod void testCreateCaseEvent() {  
    // Create test records                                         
        Case c = new Case(Subject ='Alley Repair',Address__c ='702 19TH STREET NE',FlexNotes__c ='Test CreateCaseEvents',OwnerId='00Gt0000000MCx3EAG');                
        insert c;                            
         
        case c1  = new Case(Subject ='Alley Repair',Address__c ='702 19TH STREET NE',FlexNotes__c ='Test CreateCaseEvents',OwnerId='00Gt0000000MCx3EAG');
        insert c1;        
          
    } 
}