src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Service_Request_Number__c</fullName>
        <description>Displays the correct logical Service Request Id whether the request originated in 311Force or the legacy Motorola CSR.</description>
        <formula>if(LEFT(LegacyID__c,4)=&quot;CSR-&quot;,OldCaseNumber__c,CaseNumber)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Request Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SRBulkClose_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Max_Number_of_Records_to_Process__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field will determine the number of records to process at one time for the closure page. The maximum will be 1000.</description>
        <inlineHelpText>Please enter a number between 1 - 1000. Any number greater than 1000 will be capped to 1000.</inlineHelpText>
        <label>Max Number of Records to Process</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SR Bulk Close Config</label>
</CustomObject>

src/classes/SRBulkCloseCtrlTest.cls
@isTest
public class SRBulkCloseCtrlTest { 
  public static testmethod void testImportCSVFile() {
    TestHelper.createData();
    SRBulkClose_Config__c config = SRBulkClose_Config__c.getInstance();
    config.Max_Number_of_Records_to_Process__c = 2;
    upsert config;

    SRBulkCloseCtrl ctrl = new SRBulkCloseCtrl();

    List<Case> casesList = [Select Id, Service_Request_Number__c From Case];

    String csvString = '';

    for (Case c : casesList) {
      csvString += c.Service_Request_Number__c + ',Comments here\n';
    }
    Blob csvFileBlob = Blob.valueOf(csvString);

    ctrl.csvFileBody = csvFileBlob;
    ctrl.importCSVFile();
    System.assertEquals(0, ctrl.resultCaseWrapper.size());

    config.Max_Number_of_Records_to_Process__c = 1;
    upsert config;
    ctrl.importCSVFile();
    System.assertEquals(0, ctrl.resultCaseWrapper.size());
  }
}