src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ward__c</fullName>
        <label>Ward</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Flex_Note_History__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeDescriptionSourcePart1__c</fullName>
        <label>CodeDescriptionSourcePart1</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CodeDescriptionSourcePart2__c</fullName>
        <label>CodeDescriptionSourcePart2</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note History</label>
    <nameField>
        <label>Flex Note History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flex Note Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CodeDescriptionSourcePart1__c</fullName>
        <description>Used for Legacy Data Load only</description>
        <label>CodeDescriptionSourcePart1</label>
        <length>16000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CodeDescriptionSourcePart2__c</fullName>
        <description>Used Legacy Data Load only</description>
        <label>CodeDescriptionSourcePart2</label>
        <length>16000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FlexNoteQuestionCode__c</fullName>
        <formula>FlexNote_Question__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FlexNoteQuestionCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUCServiceRequestConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is the custom setting stores parameters</description>
    <fields>
        <fullName>BulkCollectionScheduleQuestion__c</fullName>
        <description>This is for testing purpose</description>
        <label>Bulk Collection Schedule Question</label>
        <type>TextArea</type>
    </fields>
    <label>OUC ServiceRequest Config</label>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batchClassBulkCollection.cls
global class batchClassBulkCollection implements Database.Batchable<sObject> {

global batchClassBulkCollection(){}
    
    public Database.QueryLocator start(Database.BatchableContext context){
        list<ServiceRequestType__c> SRT=[Select Id FROM ServiceRequestType__c WHERE Name='S0031']; 
        string str='311-App';             
        string str1=SRT[0].id;
        string str2='open';
        string query = 'SELECT Id,SRType__c,ContactId,Ward__c FROM case WHERE  Origin=:str AND SRType__c=:str1 AND Status=:str2';  
        return Database.getQueryLocator(query);
    }
   
   /*public Database.QueryLocator call(){
        list<Flex_Note_History__c> dd= [SELECT id,CodeDescriptionSourcePart1__c,CodeDescriptionSourcePart2__c,CodeDescriptionSourcePart3__c FROM Flex_Note_History__c ];          
        system.debug('-------dd---------'+dd); 
        return null; 
   }*/
   
   global void execute(Database.BatchableContext BC, LIST<case> cas)  {
   system.debug('-------cas---------'+cas);
         list<string> listofid=new list<string>();
         string FlexNoteQuestionCode;
         list<FlexNoteQuestion__c> FNC=[SELECT Name,Questions__c FROM FlexNoteQuestion__c];
         list<OUCServiceRequestConfig__c> OSRC=[SELECT BulkCollectionScheduleQuestion__c FROM OUCServiceRequestConfig__c];
         string flexnoteQuestion=OSRC[0].BulkCollectionScheduleQuestion__c; 
         for(FlexNoteQuestion__c f:FNC){
             if(f.Questions__c.contains(flexnoteQuestion)){
                 FlexNoteQuestionCode=f.name;    
             }
             
         }
         for(case c:cas)
             listofid.add(c.id);
             for(string l:listofid)
             system.debug('-------listofid---------'+l);
             system.debug('-------FlexNoteQuestionCode---------'+FlexNoteQuestionCode);
         //string str='DE0710'; //FlexNoteQuestionCode
         list<FlexNote__c > FlexNote= new list<FlexNote__c >([SELECT Id,Answer__c,Case__c,FlexNoteQuestionCode__c from FlexNote__c  WHERE Case__c in :listofid AND FlexNoteQuestionCode__c=:FlexNoteQuestionCode]);
         list<FlexNote__c > FNcopy= new list<FlexNote__c >();
         system.debug('-------FlexNote---------'+FlexNote);  
         for(FlexNote__c fn:FlexNote){  
             if(fn.Answer__c==null || fn.Answer__c==''){                 
                 FNcopy.add(fn);                                 
             }           
         }
         system.debug('-------FNcopy---------'+FNcopy);
         
         sObject  SRHInstanceValue;
         List<string> listofContactid=new list<string>();
         Map<id, FlexNote__c> mapofConactidFlexnote = new Map<id, FlexNote__c>();
         Map<id, contact> mapofConactidContactemail = new Map<id, contact>();
         Map<contact, FlexNote__c> mapofContactEmailFlexnote = new Map<contact, FlexNote__c>();
         list<FlexNote__c> listtoupsertFlexNote=new list<FlexNote__c>();
         
         for(case c:cas)
         for(FlexNote__c fc:FNcopy)
         {
             if(fc.Case__c == c.Id && c.Ward__c!=null){                   
                     listofContactid.add(c.ContactId);
                     mapofConactidFlexnote .put(c.ContactId,fc); 
                     system.debug('cas--->'+cas);
                     system.debug('c.Ward__c---->'+c.Ward__c);
                         SRHInstanceValue=ServiceRequestsHelper.getFlexNoteDefault(c.Ward__c ,'DailyLimit'); 
                     System.debug('SRHInstanceValue-->'+SRHInstanceValue); 
                     if(SRHInstanceValue!=null){
                         System.debug('SRHInstanceValue-->'+SRHInstanceValue);
                         string strdate=String.valueOf(SRHInstanceValue.get('ScheduleDate__c'));   
                         String delims = '-+';
                         String[] tokens = strdate.split(delims); 
                         string strdate2=tokens[2];
                         String delims2 = ' +'; 
                         String[] tokens2 = strdate2.split(delims2);        
                         fc.Answer__c=tokens[1]+'/'+tokens2[0]+'/'+tokens[0];
                         listtoupsertFlexNote.add(fc);
                     }
                 //upsert fc;                   
             }            
         }
         //try{
         System.debug('listtoupsertFlexNote--->'+listtoupsertFlexNote);
             upsert listtoupsertFlexNote;
         //}
        // catch(Exception e){
            // System.debug('An exception occurred: ' + e.getMessage());
            // throw e; 
        // }
         
         list<Contact> ContactEmail= new list<Contact>([SELECT Id,Email,Schedule_Date__c from Contact WHERE id in:listofContactid]);
         EmailTemplate EmailTemplateId=[SELECT Id from EmailTemplate WHERE Name='Scheduling Date for bulk collection'];
         System.debug('EmailTemplateId--->'+EmailTemplateId);
         list<contact> listofupsertcontact=new list<contact>();
         for(Contact con:ContactEmail){
             mapofConactidContactemail.put(con.Id,con);
         }
         
         for (Id id1 : mapofConactidFlexnote.keySet())
         for (Id id2 : mapofConactidContactemail.keySet())
         {
             if(id1==id2) //id1 and id2 are Contact ids
             {
               list<string> email=new list<string>();
               mapofContactEmailFlexnote.put(mapofConactidContactemail.get(id1),mapofConactidFlexnote.get(id2));
               
               mapofConactidContactemail.get(id1).Schedule_Date__c = mapofConactidFlexnote.get(id2).Answer__c; 
               //upsert mapofConactidContactemail.get(id1);
               listofupsertcontact.add(mapofConactidContactemail.get(id1));
             }
         }
         
         try{
             upsert listofupsertcontact;
         }
         catch(Exception e){
             System.debug('An exception occurred: ' + e.getMessage());
             throw e; 
         }
         
         for(contact con:listofupsertcontact){         	
             //Sending Email to case contact email
               Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
               mail.setTargetObjectId(con.id);
               system.debug('--setTargetObjectId----'+mail);
               String[] toaddress = new String[]{con.email};
               mail.setToAddresses(toaddress);
               system.debug('--setToAddresses----'+mail);
               mail.setTemplateId(EmailTemplateId.id);
               
               if(!Test.isRunningTest()){
               		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
               }
               
               //call();
         }        
        
        
   }   

   global void finish(Database.BatchableContext BC) {       
       //calling another batch class
       /* removing execution of unrelated batch ER 2014-12-26
       batchClassFlexNoteHistory batchFNH=new batchClassFlexNoteHistory ();
       id dbi=database.executebatch(batchFNH,200);
       */
       
       //Scheduling the batch every 5 min
        Datetime sysTime = System.now();
        sysTime = sysTime.addSeconds(300);
        String chron_exp = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
        system.debug(chron_exp);
        
        System.schedule('acctBatch2Job' + sysTime.getTime(),chron_exp,new SelfSchedule());
    }
}