src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlexNotes__c</fullName>
        <label>FlexNotes (not used)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>SLAType__c</fullName>
        <description>Defines the units (ie business days, calendar days) that apply to the value entered in the SLA field.</description>
        <label>SLA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <description>a number in days based on the selected SLA type by which the service request should be completed by the servicing agency.</description>
        <inlineHelpText>in days</inlineHelpText>
        <label>SLA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batchEventCreateTest.cls
@isTest 
private class  batchEventCreateTest { 
    static testmethod void testEventBatch() {  
    // Create test records                                         
        Case c = new Case(Subject ='Alley Repair',Address__c ='702 19TH STREET NE',FlexNotes__c ='test Batch');                
        insert c;                 
        Event e = new Event(Subject ='Other', StartDateTime= system.now(), EndDateTime=system.now(),  WhatId=c.Id);          
        insert e;            
        ServiceRequestType__c  st = new  ServiceRequestType__c();     
        st.Name         ='S0016';
        st.SLAType__c   ='Business days';
        st.SLA__c       = '270';
        //  st.SRType__c    = c.id;
        insert st;                    
        Test.startTest(); 
        batchEventCreate  b = new batchEventCreate(); 
        Database.executeBatch(b); 
        Test.stopTest();   
    } 
}