src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE( Status, 
&quot;Closed&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed - Incomplete Information&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Closed)&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Opened)&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;In Progress&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Voided&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Dispute&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Open&quot;, &quot;/img/samples/flag_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;Status Flag&quot;)

&amp; &apos; &apos; &amp; TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>If(Isblank(Due_Date_Internal__c) ,CreatedDate + Activity_Type__r.SLA__c, Due_Date_Internal__c)</formula>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Comments__c</fullName>
        <label>External Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Request_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request History</label>
        <referenceTo>Service_Request_History__c</referenceTo>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Activity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Short_Name__c</fullName>
        <label>Open311 Task Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity_History__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Comments__c</fullName>
        <label>External Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Request_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request History</label>
        <referenceTo>Service_Request_History__c</referenceTo>
        <relationshipName>OUC_Activity_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Short_Name__c</fullName>
        <label>Task Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity History</label>
    <nameField>
        <label>OUC Activity HIstory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Activity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request_History__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>Case Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <label>Date/Time Opened (deprecated)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRType__c</fullName>
        <label>Service Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Incomplete Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Closed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Opened)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request History</label>
    <nameField>
        <label>Service Request History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceRequestStatusCheckController.cls
public with sharing class ServiceRequestStatusCheckController{
     
     public string Id{get;set;}
     public string requestId{get;set;}
     public string email{get;set;}
     public string email_address{get;set;}
     public Service_Request_History__c caserecord{get{system.debug('caserecord--->'+caserecord); return caserecord;}set;}
     public Boolean render{get;set;}
     public Boolean rend{get;set;}
     public Boolean home_rend{get;set;}
    // public OUC_Activity_History__c oucacthistory{get{system.debug('oucacthistory--->'+oucacthistory); return oucacthistory;}set;}
     
     public LIST<ServiceRequestType__c> servicename {get;set;}
     
     /**  
       *  constructor          
     */   
     public ServiceRequestStatusCheckController(){
        render=false; 
        rend=true; 
        home_rend =true;   
    }
    
     /**
       *       
       * To invoke getRequest and return the particular case 
       * 
       */
     public PageReference action(){
               
         
         if(requestId == null || requestId == ''){
             render=false;
             rend=true;
            
             
             ApexPages.Message error_msg = new ApexPages.Message(ApexPages.Severity.ERROR,'A service request number is required to lookup status. Please enter a valid service request number.');
             ApexPages.addMessage(error_msg);
             
             system.debug('requestId ---->');
             
             return null;
             
         }
                     
         /*if(email == null || email == ''){
             render=false;
             rend=true;
               
             
             ApexPages.Message error_msg = new ApexPages.Message(ApexPages.Severity.ERROR,'A valid email address is required to lookup status. Please enter a valid email address.');
             ApexPages.addMessage(error_msg);
             
             system.debug('requestId ---->');
             
             return null;             
           
             
         }*/
           
           
         if(requestId != null){ 
             render=true;
             rend=false;
             home_rend =false;   
             
             try{  
                 caserecord=getRequest(requestId);
                 string SrID= caserecord.SRType__c;
                 
                 servicename = [Select Service_Name__c from ServiceRequestType__c where Id=:SrID];
                 system.debug('caserecord.OUC_Activities__r --->'+caserecord.OUC_Activity_Histories__r);                 
                
               
              }catch(Exception e){
                  render=false;
                  rend=true;
                  home_rend =true; 
                  
                  ApexPages.Message error_msg = new ApexPages.Message(ApexPages.Severity.ERROR,'The service request cannot be found. Please check your entry for misspelled words.');
                  ApexPages.addMessage(error_msg);
                  system.debug('caserecord ---->');
                  
                  return null;
              
              }            
           
            system.debug('caserecordmthd ------->'+caserecord);         
           
            system.debug('caserecord in mthd ------->'+caserecord);
         }
          
         return null;
     }
     
     public static Service_Request_History__c getRequest(String requestId){
           
           List<Service_Request_History__c> cases =[Select Address__c,CaseNumber__c,CreatedDate__c,Id, 
           SRType__c,Status__c,Subject__c, (Select Completion_Date__c, Due_Date__c, External_Comments__c, 
           Id, Status__c, Task_Short_Name__c From OUC_Activity_Histories__r) 
           from Service_Request_History__c 
           WHERE CaseNumber__c=:requestId OR Id=:requestId];             
          
           system.debug('Service_Request_History__c --->'+cases ); 
                              
           if(cases.size()==0){
                //invalid requestId code provided data could not be found
                 throw new CustomException(APIConstants.NOT_FOUND); 
           }
           return cases[0];
           
    }
     
}