src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CodeDescription__c</fullName>
        <label>Code Description</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>AnswerValues__c</fullName>
        <label>Answer Values</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code (not used)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SR Activities</relationshipLabel>
        <relationshipName>OUC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <label>Public</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Object__c</fullName>
        <description>Required field - will always be set to Case.</description>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloneHistoryObjectsTest.cls
/**
 * Class containing tests for cloneServiceRequestHistory
*/


@isTest
public class CloneHistoryObjectsTest{
    private static contact con;
    private static case caserecord;
    private static FlexNoteQuestion__c Fquestion;
    private static FlexNote__c flexnote;
    private static String caseId;
    private static Id srhId;   
    
    
    private static list<Id>caseIdsList;
    private static list<FlexNote__c>fnList;
    private static list<FlexNoteQuestion__c>fnQList;
    
    private static void createData(){
      //insert contact
      con=new contact(LastName='martin',FirstName='ricky',Phone='1234567890',MobilePhone='1234567890',Email='martin@abc.com');//,Name='ricky martin');
      insert con;
      
      ServiceRequestType__c srType=new ServiceRequestType__c(Name='Test',Object__c='Case',Service_Name__c='Abandon on Private Vechicle');
      insert srType;
          
      //insert case
      caserecord=new case(Status='open',ContactId=con.Id,SRType__c=srType.Id);         
      insert caserecord;
          
      Fquestion=new FlexNoteQuestion__c(Name='FNQ-Code', Code__c='testcode',Answer_Type__c='MultiPicklist',Questions__c='Please identify the items for collection (refrigerator, household furniture, etc.)',
      AnswerValues__c='HOUSAPPL:Household Appliances (Doors off Refrigerators),FURNI001:Furniture,COMOACNA:Computer Monitors (Actual Computer not Accepted),CONDEBPR:Construction/Demolition Debris (Prohibited),INC:sample picks only'
      );
      insert Fquestion;
/*
      flexnote=new FlexNote__c(Name='testname',FlexNote_Question__c=Fquestion.id,Case__c=caserecord.id,Order__c=1,Answer__c='HOUSAPPL,FURNI001'
      ,Questions__c='Please identify the items for collection (refrigerator, household furniture, etc.)',CodeDescription__c='HOUSAPPL:Household Appliances (Doors off Refrigerators);FURNI001:Furniture;COMOACNA:Computer Monitors (Actual Computer not Accepted)'
      );
*/      
      flexnote=new FlexNote__c(FlexNote_Question__c=Fquestion.id,Case__c=caserecord.id,Order__c=1,Answer__c='HOUSAPPL,FURNI001'
      ,Questions__c='Please identify the items for collection (refrigerator, household furniture, etc.)',CodeDescription__c='HOUSAPPL:Household Appliances (Doors off Refrigerators);FURNI001:Furniture;COMOACNA:Computer Monitors (Actual Computer not Accepted)'
      );
      
      
      insert flexnote;    
      
      
      OUC_Activity__c oucActivity= new OUC_Activity__c(Case__c=caserecord.Id,Public__c='test');
      insert oucActivity;
      
      
      
      
      
      
      
      
      caseIdsList=new list<Id>{caserecord.Id};
      fnList=new list<FlexNote__c>{flexnote};
      fnQList=new list<FlexNoteQuestion__c>{Fquestion};
    }
    
    
    public static testmethod void cloneHistoryObjectTest(){
        createData();
        Test.startTest();
            CloneHistoryObjects.cloneServiceRequestHistory(caseIdsList);
        Test.stopTest();
    }
    
    public static testmethod void serviceRequestHelperTest(){
        createData();
        Test.startTest();
            //ServiceRequestsHelper.startFlexNoteProcess(fnList,fnQList);
        Test.stopTest();
    }
    
    
    
    
       
}