src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE( Status, 
&quot;Closed&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Closed - Incomplete Information&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Closed)&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Duplicate (Opened)&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;In Progress&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Voided&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;Dispute&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;Open&quot;, &quot;/img/samples/flag_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;Status Flag&quot;)

&amp; &apos; &apos; &amp; TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Decode_Object__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Decode Object</label>
    <nameField>
        <label>Decode Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decode Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flex_Note_History__c.object
<CustomObject>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note History</label>
    <nameField>
        <label>Flex Note History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flex Note Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question (deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>AnswerValues__c</fullName>
        <label>Answer Values</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Answer_Values__c</fullName>
        <label>Answer Values(delete)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code (not used)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question(delete)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Activity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SR Activity</label>
    <nameField>
        <displayFormat>ACT-{00000000}</displayFormat>
        <label>SR Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OUC_Activity_History__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SR Activity History</label>
    <nameField>
        <label>OUC Activity HIstory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Activity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request_History__c.object
<CustomObject>
    <fields>
        <fullName>SRType__c</fullName>
        <label>Service Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Incomplete Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Closed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate (Opened)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request History</label>
    <nameField>
        <label>Service Request History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Default_Method__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Method</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>311-App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Priority__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Status__c</fullName>
        <description>If a value is entered here, it will be used to set this field on a new Service Request when this SR Type is created.</description>
        <label>Default Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Required field - will always be set to Case.</description>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SR_Alert_Message__c</fullName>
        <description>Text entered displays at top of Agent Console when SR Type is selected.</description>
        <label>SR Alert Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestTypeFlexNote__c.object
<CustomObject>
    <description>Contains all the flex notes that related to a service request type and attributes specific to it.</description>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>Service Request Type Flex Notes</relationshipLabel>
        <relationshipName>Service_Request_Type_Flex_Notes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Service Request Type Flex Notes</relationshipLabel>
        <relationshipName>Service_Request_Type_Flex_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Request Type Flex Note</label>
    <nameField>
        <displayFormat>SRFN-{0000}</displayFormat>
        <label>Service Request Type FlexNote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Type Flex Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestHelper.cls
public with sharing class TestHelper{
    
    public static contact cont;
    public static ServiceRequestType__c serviceType1;
    public static case caseRrd;
    public static list<case> caseRrdList;
    public static list<FlexNoteQuestion__c> flexNoteQuestList;
    public static list<FlexNote__c>AnswersList;
    public static list<ServiceRequestTypeFlexNote__c>sRTypeJunc;   
    public static string APIKey;
    
    
    public static void createData(){

        Contact con=new Contact(FirstName='Mars',LastName='bruno', email='testContact@abc.com',Phone='1234567890');
        insert con;
        cont=con;
        
        Decode_Object__c obj = new Decode_Object__c(code__c='A123',value__c='this is a test ans');
        insert obj;
        
        
        ServiceRequestType__c sRT=new ServiceRequestType__c(Name='DMV19',Object__c='Case',Service_Name__c='Abandoned Vehicle- On Private Property',Default_Status__c='New',Default_Priority__c='Standard',Default_Method__c='Phone',SR_Alert_Message__c='Test Message');
        insert sRT;
        serviceType1=sRT;
        
        flexNoteQuestList=new list<FlexNoteQuestion__c>();
        
        FlexNoteQuestion__c fNQuestion=new FlexNoteQuestion__c(Object_Name__c='Case',Questions__c='This is the test Question',Answer_Type__c='MultiPicklist' ,Name='Test1',AnswerValues__c='test1:a1,test2:a2');//,Answer_Values__c='test1:a1,test2:a2');//Question__c='This is the test Question'
         
        FlexNoteQuestion__c fNQuestion1=new FlexNoteQuestion__c(Object_Name__c='Case',Questions__c='This is the test',Answer_Type__c='Text' ,Name='Test2');//,Answer_Values__c='test1:a1,test2:a2');//,Question__c='This is the test'
       
        FlexNoteQuestion__c fNQuestion2=new FlexNoteQuestion__c(Object_Name__c='Case',Questions__c='This is the test picklist',Answer_Type__c='Picklist' ,Name='Test3',AnswerValues__c='test1:a1,test2:a2');//,Answer_Values__c='test1:a1,test2:a2');//Question__c='This is the test picklist'
       
        
        flexNoteQuestList.add(fnQuestion);
        flexNoteQuestList.add(fnQuestion1);
        flexNoteQuestList.add(fnQuestion2);
        
        insert flexNoteQuestList;
        
        sRTypeJunc=new list<ServiceRequestTypeFlexNote__c>();
        
        
        ServiceRequestTypeFlexNote__c sRTypeFNRelation=new ServiceRequestTypeFlexNote__c(Service_Request_Type__c=sRT.Id,FlexNote_Question__c=fnQuestion.Id,Order__c='1',IsRequired__c=true);
        
        ServiceRequestTypeFlexNote__c sRTypeFNRelation1=new ServiceRequestTypeFlexNote__c(Service_Request_Type__c=sRT.Id,FlexNote_Question__c=fNQuestion2.Id,Order__c='1');
      
        sRTypeJunc.add(sRTypeFNRelation);
        sRTypeJunc.add(sRTypeFNRelation1);
        
        
        insert sRTypeJunc;
        
        caseRrdList=new list<case>();
       
        Case c=new Case(Origin='Phone',Status='New',ContactId=con.Id,SRType__c=sRT.Id);
        insert c;      
        caseRrd=c;
        
        caseRrdList.add(caseRrd);

        Case c2=new Case(Origin='Phone',Status='Open',LegacyID__c='CSR-test',ContactId=con.Id,SRType__c=sRT.Id);
        insert c2;      
        
        //caseRrdList.add(c2);
        
        AnswersList=new list<FlexNote__c>();
        
        FlexNote__c fn=new FlexNote__c(Case__c=c.Id,FlexNote_Question__c=fNQuestion.Id,Answer__c='test1:a1',Questions__c=fNQuestion.Question__c);//Question__c=fNQuestion.Question__c //Is_Answer__c='test1:a1',
        FlexNote__c fn1=new FlexNote__c(Case__c=c.Id,FlexNote_Question__c=fNQuestion1.Id,Answer__c='test1:a1',Questions__c=fNQuestion1.Question__c);//,Is_Answer__c='test1:a1'..,Question__c=fNQuestion.Question__c,

        FlexNote__c fn2=new FlexNote__c(Case__c=c2.Id,FlexNote_Question__c=fNQuestion.Id,LegacyId__c='CSR-test1',Answer__c='test1:a1',CodeDescriptionSourcePart1__c='CODE1,CODE2',CodeDescriptionSourcePart2__c='value1,othervalue',Questions__c=fNQuestion.Question__c);//Question__c=fNQuestion.Question__c //Is_Answer__c='test1:a1',
        FlexNote__c fn3=new FlexNote__c(Case__c=c2.Id,FlexNote_Question__c=fNQuestion1.Id,LegacyId__c='CSR-test2422',Answer__c='otherwanswertest1:a1',Questions__c=fNQuestion1.Question__c);//,Is_Answer__c='test1:a1'..,Question__c=fNQuestion.Question__c,
       
        AnswersList.add(fn);
        AnswersList.add(fn1);    
        AnswersList.add(fn2);
        AnswersList.add(fn3);    
        insert AnswersList;
        
        OUC_Activity__c oucActivity= new OUC_Activity__c(Case__c=c.Id);
      	insert oucActivity;
      
         
        Service_Request_History__c h = new Service_Request_History__c(Origin__c='Phone',Status__c='New',DateTimeOpened__c=DateTime.valueofGMT('2015-01-01 00:01:02'),IsClosed__c=true);
        insert h;
        Service_Request_History__c h2 = new Service_Request_History__c(Origin__c='Phone',Status__c='New',DateTimeOpened__c=DateTime.valueofGMT('2015-01-01 00:02:03'),IsClosed__c=false);
        insert h2;
        
        Map<String,String> code = new Map<String,String>();
        code.put('FYTRS','This is a test');
        List<Flex_Note_History__c> hL= new List<Flex_Note_History__c>();
        Flex_Note_History__c fnh=new Flex_Note_History__c(CodeDescription__c= JSON.serialize(code),Service_Request_History__c=h.Id,Flex_Note_Id__c=fNQuestion.Id,Answer__c='test1:a1',Questions__c=fNQuestion.Question__c);//Question__c=fNQuestion.Question__c //Is_Answer__c='test1:a1',
        Flex_Note_History__c fnh1=new Flex_Note_History__c(CodeDescription__c= JSON.serialize(code),Service_Request_History__c=h.Id,Flex_Note_Id__c=fNQuestion1.Id,Answer__c='test1:a1',Questions__c=fNQuestion.Question__c);//,Is_Answer__c='test1:a1'..,Question__c=fNQuestion.Question__c,
        Flex_Note_History__c fnh2=new Flex_Note_History__c(CodeDescriptionSourcePart1__c='CODE1,CODE2',CodeDescriptionSourcePart2__c='value1,Value22',Service_Request_History__c=h.Id,Flex_Note_Id__c='CSR-test1234',Answer__c='test1:a1',Questions__c=fNQuestion.Question__c);//,Is_Answer__c='test1:a1'..,Question__c=fNQuestion.Question__c,
        
        hL.add(fnh);
        hL.add(fnh1);
        hl.add(fnh2);
        
        insert hL; 
        
        OUC_Activity_History__c oucActivity2= new OUC_Activity_History__c(Service_Request_History__c=h.Id);
      	insert oucActivity2;
      	
        OUC_Activity_History__c oucActivity3= new OUC_Activity_History__c(Service_Request_History__c=h2.Id);
      	insert oucActivity3;

      	string thisKey = 'class2Private';
      	Open311ApiKeyConfig__c key = new Open311ApiKeyConfig__c(ApiKey__c=thisKey,Private__c=true,Usage_Limit_Allocation__c=1000);
      	insert key;
        System.debug('----> Test Api Key: ' + key);
      	APIKey = thisKey;
         
    }
      
}