src/objects/Decode_Object__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Decode Object</label>
    <nameField>
        <label>Decode Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decode Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>AnswerValues__c</fullName>
        <label>Answer Values</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code (not used)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>Jurisdiction__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Citizen_Web_Intake__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this SR Type will be available for use on the Citizen Portal.</description>
        <label>Allow Citizen Web Intake</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Originally intended for internal use but is not used.</description>
        <label>Description (not used)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Name__c</fullName>
        <description>If populated, this is the service name displayed on the citizen portal.</description>
        <label>External Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Note_Count__c</fullName>
        <label>Flex Note Count</label>
        <summaryForeignKey>ServiceRequestTypeFlexNote__c.Service_Request_Type__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <label>Keywords</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LongExternalDescription__c</fullName>
        <label>External Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SLAType__c</fullName>
        <description>Defines the units (ie business days, calendar days) that apply to the value entered in the SLA field.</description>
        <label>SLA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <description>a number in days based on the selected SLA type by which the service request should be completed by the servicing agency.</description>
        <inlineHelpText>in days</inlineHelpText>
        <label>SLA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceLocationRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Location Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestTypeFlexNote__c.object
<CustomObject>
    <description>Contains all the flex notes that related to a service request type and attributes specific to it.</description>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>Service Request Type Flex Notes</relationshipLabel>
        <relationshipName>Service_Request_Type_Flex_Notes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>IsRequiredQuestion__c</fullName>
        <formula>/*Any of them is true then formula shuld return true*/
/*if flexnoteQuestion is made true or junction record made true than question is required*/




if(OR(FlexNote_Question__r.Required__c , isRequired__c ) ,true,false )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type Flex Note</label>
    <nameField>
        <displayFormat>SRFN-{0000}</displayFormat>
        <label>Service Request Type FlexNote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Type Flex Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Open311_ServicesAPIResponse.cls
global  class Open311_ServicesAPIResponse {
	
	static map<string,string> datatype_map = new map<string,string>{'text'=>'string','multipicklist'=>'multivaluelist','picklist'=>'singlevaluelist','textarea'=>'text','integer'=>'number','date/time'=>'datetime', 'date'=> 'date'};
    
    public static String sendJSONResponse(ServiceRequestType__c obj,List<ServicesHelper.ServiceRequestTypeFlexNote> flexNotes){
          JSONGenerator gen = JSON.createGenerator(true);
          gen.writeStartObject();
          gen.writeStringField('service_code',obj.name);
          
          //add the attributes 
          gen.writeFieldName('attributes');            
               gen.writeStartArray();
               for(ServicesHelper.ServiceRequestTypeFlexNote elem:flexNotes){
               		ServiceRequestTypeFlexNote__c fn =elem.flexnote;
                    gen.writeStartObject();
                        gen.writeStringField('variable',!String.isEmpty(fn.FlexNote_Question__r.Answer_Type__c)?'true':'false');  
                        gen.writeStringField('code',stringValue(fn.FlexNote_Question__r.Name));  
                        string dt=fn.FlexNote_Question__c!=null && fn.FlexNote_Question__r.Answer_Type__c!=null ? datatype_map.get(fn.FlexNote_Question__r.Answer_Type__c.toLowerCase()):'';
                        gen.writeStringField('datatype',stringValue(dt));  
                        gen.writeStringField('required',stringValue(string.valueof(fn.IsRequiredQuestion__c)));  
                        gen.writeStringField('order',stringValue(string.valueof(fn.order__c)));  
                        gen.writeStringField('description',stringValue(fn.FlexNote_Question__r.Questions__c )); 
                        
                        if(fn.FlexNote_Question__r.AnswerValues__c!=null){
	                        gen.writeFieldName('values');  
	                        gen.writeStartArray();
	                        	List<String> valueList= new List<String>();
			               		if(elem.keyValueAns!=null){
			               			for(Decode_Object__c dc:elem.keyValueAns)
			               				valueList.add(dc.code__c+':'+dc.value__c);
			               		}
			               		
	                        	List<String> values = elem.keyValueAns!=null ? valueList:fn.FlexNote_Question__r.AnswerValues__c.split(',');
	                        	for(String val:values){
	                        		gen.writeStartObject();
	                        			gen.writeFieldName('value');gen.writeStartArray(); gen.writeStartObject();
			                                gen.writeStringField('key',!val.contains('{!')?val.split(':')[0]:'');  
			                                gen.writeStringField('name',val.split(':').size()>1 && !val.contains('{!')?val.split(':')[1]:'');  
	                            		gen.writeEndObject();gen.writeEndArray();
	                            	gen.writeEndObject();
	                        	}
	                          
	                        gen.writeEndArray();
                        }     
                    gen.writeEndObject();
               }
               gen.writeEndArray();
          gen.writeEndObject();
          return gen.getAsString();
    }
        
    public static String sendJSONResponse(List<ServiceRequestType__c> obj,Boolean isPrivate){

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartArray();
        for(ServiceRequestType__c req:obj){
        	
        	if(req.Allow_Citizen_Web_Intake__c==false)
        		continue;
        		
            gen.writeStartObject();
                gen.writeStringField('service_code',stringValue(req.name));  
                gen.writeStringField('service_name',stringValue(req.External_Name__c));
                gen.writeStringField('agency',stringValue(req.Agency__c));
                gen.writeStringField('metadata',req.Flex_Note_Count__c>0?'true':'false');
                gen.writeStringField('description',stringValue(req.description__c));  
                gen.writeStringField('long_external_description',stringValue(req.LongExternalDescription__c));  
                gen.writeStringField('group',stringValue(req.group__c));   
                gen.writeStringField('keywords',stringValue(req.keywords__c));
                gen.writeStringField('external_name',stringValue(req.External_Name__c));
                gen.writeStringField('sla',stringValue(req.SLA__c));        
                gen.writeStringField('sla_type',stringValue(req.SLAType__c)); 
                gen.writeStringField('service_location_required',String.valueOf(req.ServiceLocationRequired__c));
                
            	/*if(isPrivate)
                {
                    gen.writeStringField('external_name',stringValue(req.External_Name__c));
                    gen.writeStringField('sla',stringValue(req.SLA__c));        
                    gen.writeStringField('sla_type',stringValue(req.SLAType__c)); 
                    gen.writeStringField('service_location_required',String.valueOf(req.ServiceLocationRequired__c)); 
                }*/
            gen.writeEndObject();
        }
        gen.writeEndArray();
        return gen.getAsString(); 
        
    }
    
    public static String sendXMLResponse(ServiceRequestType__c obj,List<ServicesHelper.ServiceRequestTypeFlexNote> flexNotes){
       	Dom.Document doc = new Dom.Document();
        Dom.Xmlnode rootNode = doc.createRootElement('service_definition', null, null); 
        Dom.Xmlnode reqNode = rootNode.addChildElement('service_code', null, null).addTextNode(stringValue(obj.name));
        Dom.Xmlnode attrNode = rootNode.addChildElement('attributes', null, null);
        for(ServicesHelper.ServiceRequestTypeFlexNote elem:flexNotes){
        	ServiceRequestTypeFlexNote__c fn =elem.flexnote;
        	Dom.Xmlnode  childNode = attrNode.addChildElement('attribute', null, null);
        	childNode.addChildElement('variable', null, null).addTextNode(!String.isEmpty(fn.FlexNote_Question__r.Answer_Type__c)?'true':'false');
        	childNode.addChildElement('code', null, null).addTextNode(stringValue(fn.FlexNote_Question__r.Name));
        	childNode.addChildElement('datatype', null, null).addTextNode(fn.FlexNote_Question__r.Answer_Type__c!=null? stringValue(datatype_map.get(fn.FlexNote_Question__r.Answer_Type__c.toLowerCase())):'');
        	childNode.addChildElement('required', null, null).addTextNode(stringValue(String.valueof(fn.IsRequiredQuestion__c)));
        	childNode.addChildElement('order', null, null).addTextNode(stringValue(String.valueof(fn.order__c)));
        	childNode.addChildElement('description', null, null).addTextNode(stringValue(fn.FlexNote_Question__r.Questions__c));
        	
        	if(fn.FlexNote_Question__r.AnswerValues__c!=null){
                	Dom.Xmlnode  valueNode = childNode.addChildElement('values', null, null);
               		List<String> valueList= new List<String>();
               		if(elem.keyValueAns!=null){
               			for(Decode_Object__c dc:elem.keyValueAns)
               				valueList.add(dc.code__c+':'+dc.value__c);
               		}
               		
                	List<String> values = elem.keyValueAns!=null ? valueList: fn.FlexNote_Question__r.AnswerValues__c.split(',');
                	for(String val:values){
                		Dom.Xmlnode valNode = valueNode.addChildElement('value', null, null);
                        valNode.addChildElement('key', null, null).addTextNode(!val.contains('{!')? val.split(':')[0]:'');   
                        valNode.addChildElement('name', null, null).addTextNode(val.split(':').size()>1 && !val.contains('{!') ?val.split(':')[1]:''); 
                           
                	}                                 
            }     
        
        
        }
        return doc.toXMLString();
    }
        
    public static String sendXMLResponse(List<ServiceRequestType__c> obj,Boolean isPrivate){
        Dom.Document doc = new Dom.Document();
        Dom.Xmlnode rootNode = doc.createRootElement('services', null, null); 
        
        for(ServiceRequestType__c req:obj){ 
            if(req.Allow_Citizen_Web_Intake__c==false)
        		continue;
            Dom.Xmlnode reqNode = rootNode.addChildElement('service', null, null);
            reqNode.addChildElement('service_code', null, null).addTextNode(req.name==null? '':req.name);
            reqNode.addChildElement('service_name', null, null).addTextNode(req.External_Name__c==null?'':req.External_Name__c);
            reqNode.addChildElement('description', null, null).addTextNode(req.description__c==null ?'':req.description__c); 
            reqNode.addChildElement('metadata', null, null).addTextNode(req.Flex_Note_Count__c>0?'true':'false');                   
            //reqNode.addChildElement('type', null, null).addTextNode(req.type__c==null?'':req.type__c); 
            reqNode.addChildElement('keywords', null, null).addTextNode(req.keywords__c!=null ? req.keywords__c:''); 
            reqNode.addChildElement('group', null, null).addTextNode(req.group__c==null?'':req.group__c);
            reqNode.addChildElement('external_name', null, null).addTextNode(req.External_Name__c==null? '':req.External_Name__c);
            reqNode.addChildElement('sla', null, null).addTextNode(req.SLA__c==null? '':req.SLA__c);
            reqNode.addChildElement('sla_type', null, null).addTextNode(req.SLAType__c==null? '':req.SLAType__c);
            reqNode.addChildElement('service_location_required', null, null).addTextNode(req.ServiceLocationRequired__c==true? 'true':'false');

            
            /*if(isPrivate)
                {
                    reqNode.addChildElement('external_name', null, null).addTextNode(req.External_Name__c==null? '':req.External_Name__c);
                    reqNode.addChildElement('sla', null, null).addTextNode(req.SLA__c==null? '':req.SLA__c);
                    reqNode.addChildElement('sla_type', null, null).addTextNode(req.SLAType__c==null? '':req.SLAType__c);
                    reqNode.addChildElement('service_location_required', null, null).addTextNode(req.ServiceLocationRequired__c==true? 'true':'false');
                }*/
        }           
        return doc.toXMLString();
    } 
    
    public static string stringValue(String val){
    	return val==null ? '':val;
    }
   
}