src/objects/Decode_Object__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Decode Object</label>
    <nameField>
        <label>Decode Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decode Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>AnswerValues__c</fullName>
        <label>Answer Values</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code (not used)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Jurisdiction__c.object
<CustomObject>
    <description>Stores Agency and Department Information of DC Government.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <description>This Field contains DC Government Agency Abbreviations like -  DDOT, DPW</description>
        <label>Servicing Agency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Agency Dept Code</label>
    <nameField>
        <label>Agency Dept Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Dept Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>Jurisdiction__r.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Citizen_Web_Intake__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this SR Type will be available for use on the Citizen Portal.</description>
        <label>Allow Citizen Web Intake</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Originally intended for internal use but is not used.</description>
        <label>Description (not used)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Description__c</fullName>
        <label>External Description(To Be Deleted)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Name__c</fullName>
        <description>If populated, this is the service name displayed on the citizen portal.</description>
        <label>External Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Note_Count__c</fullName>
        <label>Flex Note Count</label>
        <summaryForeignKey>ServiceRequestTypeFlexNote__c.Service_Request_Type__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Flex_Notes_Link_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not used.</description>
        <label>Flex Notes Link Indicator (not used)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on legacy CSR, this field defines the Agency and sub-department at that agency responsible for servicing this SR Type.</description>
        <label>Agency Dept Code</label>
        <referenceTo>Jurisdiction__c</referenceTo>
        <relationshipLabel>Service Request Types</relationshipLabel>
        <relationshipName>Service_Request_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <label>Keywords</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LongExternalDescription__c</fullName>
        <label>External Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SLAType__c</fullName>
        <description>Defines the units (ie business days, calendar days) that apply to the value entered in the SLA field.</description>
        <label>SLA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <description>a number in days based on the selected SLA type by which the service request should be completed by the servicing agency.</description>
        <inlineHelpText>in days</inlineHelpText>
        <label>SLA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceLocationRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Location Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType_Jurisdiction__c.object
<CustomObject>
    <description>Junction Object between Service Request Type and Jurisdiction and contains SLAs</description>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <referenceTo>Jurisdiction__c</referenceTo>
        <relationshipLabel>Service Request Type  Jurisdictions</relationshipLabel>
        <relationshipName>ServiceRequestType_Jurisdictions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <description>Stores SLAs for a Service Request Type and Agency and Department in Jurisdiction.</description>
        <label>SLA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRequestType__c</fullName>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Service Request Type  Jurisdictions</relationshipLabel>
        <relationshipName>Service_Request_Type_Jurisdictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service Request Type  Jurisdiction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Type  Jurisdictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceRequestTypeFlexNote__c.object
<CustomObject>
    <description>Contains all the flex notes that related to a service request type and attributes specific to it.</description>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>Service Request Type Flex Notes</relationshipLabel>
        <relationshipName>Service_Request_Type_Flex_Notes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>IsRequiredQuestion__c</fullName>
        <formula>/*Any of them is true then formula shuld return true*/
/*if flexnoteQuestion is made true or junction record made true than question is required*/




if(OR(FlexNote_Question__r.Required__c , isRequired__c ) ,true,false )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <referenceTo>ServiceRequestType__c</referenceTo>
        <relationshipLabel>Service Request Type Flex Notes</relationshipLabel>
        <relationshipName>Service_Request_Type_Flex_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Request Type Flex Note</label>
    <nameField>
        <displayFormat>SRFN-{0000}</displayFormat>
        <label>Service Request Type FlexNote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Type Flex Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServicesHelper.cls
/*
  
  Helper class: contains all the required method for service apis

*/
public class ServicesHelper{
        
       /**
       * Queries for the specified Service by serviceCode and returns the corresponding
       * response object.
       *
       * @param id  Service's serviceCode
       * @return    A response version of the matching Service.
       *            If no records are found, it will simply return a custom error message that the service code
                    is invalid
       */
        public static ServiceRequestType__c getService(String serviceCode){
            List<ServiceRequestType__c> srtypes= [
                Select 
                  Id, 
                  Name, 
                  Service_Name__c, 
                  External_Name__c, 
                  Flex_Note_Count__c, 
                  External_Description__c, 
                  Flex_Notes_Link_Indicator__c, 
                  Group__c, 
                  Keywords__c, 
                  Description__c, 
                  LongExternalDescription__c,
                  Agency__c, 
                  SLA__c,
                  SLAType__c,
                  ServiceLocationRequired__c
                From 
                  ServiceRequestType__c 
                Where 
                  Name=:serviceCode 
                LIMIT 1
            ];
            
            if(srtypes.isEmpty()){
                //invalid service code provided data could not be found
                throw new CustomException(APIConstants.NOT_FOUND);          
            }
            return srtypes[0]; 
        } 
        
    /**
       * Queries for the specified Service Flexnotes by serviceCode and returns the corresponding
       * response object.
       *
       * @param id  Service's serviceCode
       * @return    A response version of the matching Service Flexnotes.
       *            If no records are found, it will simply return null
       */
        public static List<ServiceRequestTypeFlexNote__c> getServiceMetadata(String serviceCode){
                
                return [Select FlexNote_Question__r.Answer_Type__c,FlexNote_Question__r.AnswerValues__c,FlexNote_Question__c,Order__c,
                        FlexNote_Question__r.Name,FlexNote_Question__r.Questions__c ,FlexNote_Question__r.Required__c, isRequired__c, IsRequiredQuestion__c                     
                        FROM ServiceRequestTypeFlexNote__c WHERE Service_Request_Type__r.Name=:serviceCode 
                ];
                
        }
        
        /**
       * Queries for the specified Service Flexnotes by serviceCode and returns the corresponding
       * response object.
       *
       * @param id  Service's serviceCode
       * @return    A response version of the matching Service Flexnotes along with decode object that contains answers if any
       *            If no records are found, it will simply return null
       */
        public static List<ServiceRequestTypeFlexNote> getServiceMetadata2(String serviceCode){
                
                List<ServiceRequestTypeFlexNote> response = new List<ServiceRequestTypeFlexNote>();
                
                List<ServiceRequestTypeFlexNote__c> notes = [Select FlexNote_Question__r.Answer_Type__c,FlexNote_Question__r.AnswerValues__c,FlexNote_Question__c,Order__c,
                        FlexNote_Question__r.Name,FlexNote_Question__r.Questions__c ,FlexNote_Question__r.Required__c, isRequired__c, IsRequiredQuestion__c                      
                        FROM ServiceRequestTypeFlexNote__c WHERE Service_Request_Type__r.Name=:serviceCode 
                ];
                Map<String,List<Decode_Object__c>> answerDcodeMap= new Map<String,List<Decode_Object__c>>();
                if(notes.size()>0){
                	Set<STring> nameValues = new Set<STring>();
                	for(ServiceRequestTypeFlexNote__c n:notes){
                		nameValues.add(n.FlexNote_Question__r.AnswerValues__c);
                	}

                	for(Decode_Object__c dc:[Select Name,Code__c,Value__c from Decode_Object__c WHERE Name IN:nameValues]){
                		List<Decode_Object__c> objs= answerDcodeMap.get(dc.name)!=null ?answerDcodeMap.get(dc.name):new List<Decode_Object__c>();
                		objs.add(dc);
                		answerDcodeMap.put(dc.name,objs);
                	}
                	
                }
                
                for(ServiceRequestTypeFlexNote__c n:notes){
                	response.add( new ServiceRequestTypeFlexNote(n,answerDcodeMap.get(n.FlexNote_Question__r.AnswerValues__c)));
                }
                return response;
                
        }
        
        /**
       * Queries for list of Services records and and returns the corresponding
       * response object (list of Service).  If any non-null parameters are 
       * provided, the list will be filtered by the specified field.
       *
       * @param jurisdiction_id    Id of jurisdiction
       * @return              Collection of Service objects, as an list
       */
        public static List<ServiceRequestType__c> listAllServices(String jurisdiction_id ){
            
            String query = 'Select Id, Name, Service_Name__c, External_Name__c, External_Description__c, Flex_Notes_Link_Indicator__c, Flex_Note_Count__c,group__c,keywords__c,description__c,Allow_Citizen_Web_Intake__c, LongExternalDescription__c, Agency__c, SLA__c, SLAType__c, ServiceLocationRequired__c FROM ServiceRequestType__c';
            
            /*if(jurisdiction_id!=null){
                query +=' WHERE Id IN (Select ServiceRequestType__c FROM ServiceRequestType_Jurisdiction__c WHERE Jurisdiction__r.Name=\''+jurisdiction_id+'\')';
            }*/
            query += ' Order By External_Name__c ASC';
            
            return database.query(query);
        }
        
        public class ServiceRequestTypeFlexNote{
        	public ServiceRequestTypeFlexNote__c flexnote {get;set;}
        	public List<Decode_Object__c> keyValueAns {get;set;}
        	
        	public ServiceRequestTypeFlexNote(ServiceRequestTypeFlexNote__c fn,List<Decode_Object__c> ans){
        		flexnote = fn;
        		keyValueAns = ans;
        	}
        }
        
        
}