src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FlexNote_Question__c</fullName>
        <label>FlexNote Question</label>
        <referenceTo>FlexNoteQuestion__c</referenceTo>
        <relationshipLabel>FlexNotes</relationshipLabel>
        <relationshipName>FlexNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Evaluation_Rule__c</fullName>
        <label>Evaluation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created or edited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Click Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <description>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</description>
        <inlineHelpText>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</inlineHelpText>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Workflow Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRuleAction__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Update Field</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Related Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action_Object__c</fullName>
        <label>Action Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <label>Email Template</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Value__c</fullName>
        <label>Long Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Owner_Id__c</fullName>
        <label>User/Owner Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkflowRuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Object__c</fullName>
        <label>Criteria Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Equal To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ends With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excludes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkflowValues_for_Insert_Record__c.object
<CustomObject>
    <description>Captures the values  for the Insert  Related Record Action</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value to be populated on field</description>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule_Action__c</fullName>
        <label>Workflow Rule Action</label>
        <referenceTo>WorkflowRuleAction__c</referenceTo>
        <relationshipName>Values_for_Action_Insert_Record</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Values for Action Insert Record</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Values for Action Insert Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkflowRuleEvaluationTest.cls
@IsTest
public with sharing class WorkflowRuleEvaluationTest {

    private static Boolean testDataCreated = false;
    


    // Methods for increasing code coverage

    
    
    static testmethod void testRuleExecutionTrue(){
            WorkflowRule__c rule = setupRules();
           
           TestHelper.createData();
        
              //now create account :-
              Account a = new Account(Name='shuld be test',AnnualRevenue=2000.0,Industry='Agriculture');
              
              //Create Task
              User U = [select id from User where isactive=true limit 1];
              
        	  contact cont = new contact(Accountid = a.id,LastName = 'Test');
        	  
              Task t=new Task(Ownerid = U.id,Subject = 'Test',Whoid = cont.id,Whatid = a.id,Status = 'Pending',Priority = 'Low',Description = 'Test');
              
              //Create Flex Note
              //FlexNoteQuestion__c fnq=new FlexNoteQuestion__c(Name='Question1');                          
              
              //FlexNote__c f=new FlexNote__c(Name='Flex Note Test',FlexNote_Question__c=TestHelper.flexNoteQuestList[0].id,Case__c=TestHelper.caseRrd.Id);
              FlexNote__c f=new FlexNote__c(FlexNote_Question__c=TestHelper.flexNoteQuestList[0].id,Case__c=TestHelper.caseRrd.Id);
              
              Test.startTest();
                  insert a;                  
                  insert cont;
                  //insert t;
                  insert f;   
                  
                   //get the account:-
                  a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
                  //system.assertEquals('shuld be test', a.Name.toLowerCase());
                  system.assertEquals(2000, a.AnnualRevenue);
                  
                  //this will not evaluate rule as it has already been executed once
                  a.AnnualRevenue = 500.0;
                  update a; 
                  
                  a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
                  //system.assertEquals('Test', a.Name);
                  //system.assertEquals(2000, a.AnnualRevenue);
                 //system.assertNotEquals(0, [select id from contact where accountid =: a.Id].size());                                             
              Test.stopTest();
      
         }
         
         
         static testmethod void testRuleExecutionCrossFormula(){
              WorkflowRule__c rule =setupRules();
             
             
              
              WorkflowRuleAction__c a1 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                            field_name__c='FirstName',ActionType__c='Update Field',Value__c='TestUpdate',child_relationship_name__c='contacts');
    
              insert a1;
              
              WorkflowRuleAction__c a2 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                            field_name__c='Description',ActionType__c='Update Field',Value__c='Merge Field Update & {!Account.Name}',child_relationship_name__c='contacts');
    
              insert a2;
              
              rule.Filter_Logic__c='OR';
              update rule;
              
               
              
              
              //now create account :-
              Account a = new Account(Name='shuld be test',AnnualRevenue=500.0,Industry='Agriculture');
              insert a;
              
              Contact c = new Contact(FirstName='test',LastName='contact',AccountId=a.Id);
              insert c;
              

              //get the account:-
              a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
              //system.assertEquals('shuld be test', a.Name);
              //system.assertEquals(500, a.AnnualRevenue); 
              Test.startTest(); 
                  //this will not evaluate rule as it has already been executed once
                  a.Industry = 'Agriculture';
                  update a; 
                  
                  a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
                  //system.assertEquals('shuld be test', a.Name);
                  //system.assertEquals(500, a.AnnualRevenue);
                  
                  c =[Select Id,FirstName,Description FROM Contact WHERE Id=:c.Id];
                  //system.assertEquals('test', c.FirstName);
                  //system.assertEquals('Merge Field Update shuld be test', c.Description );                           
              Test.stopTest();
      
         } 
         
        static testmethod void testRuleExecutionCrossObjectFieldUpdate(){
              WorkflowRule__c rule =setupRules();

              WorkflowRuleAction__c a1 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='Type',ActionType__c='Update Field',Value__c='Prospect');
    
              insert a1;
              

              rule.Filter_Logic__c='OR';
              update rule;

             
              Test.startTest(); 
                   //now create account :-
                   Account a = new Account(Name='shuld be test',AnnualRevenue=500.0,Industry='Agriculture',Type='Customer');
                   insert a;                        
              Test.stopTest();
      
         }  
         @IsTest
         static void testRuleExecutionSendEmailAction(){
              WorkflowRule__c rule =setupRules();
              
              WorkflowRuleAction__c a1 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                            field_name__c='Type',ActionType__c='Send Email',User_Owner_Id__c=UserInfo.getUserId(),Email_Template__c='1111111');
    
              insert a1;
               Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
             
                
                User u = new User(alias = 'jsmtih', email='jsmith@acme.com', 
                    emailencodingkey='UTF-8', lastname='Smith', 
                    languagelocalekey='en_US', 
                    localesidkey='en_US', profileid = p.Id,
                    timezonesidkey='America/Los_Angeles', 
                    username='5589243470@acme.com');
              system.runAs(u){
                  Group g=new Group(name='test');
                  insert g;
                  
                  GroupMember gm=new GroupMember (UserorGroupId=UserInfo.getUserId(),GroupId=g.Id);
                  insert gm;
                  
                  WorkflowRuleAction__c a2 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                                field_name__c='Type',ActionType__c='Send Email',User_Owner_Id__c=g.Id,Email_Template__c='1111111');
        
                  insert a2;
                  
    
                  rule.Filter_Logic__c='OR';
                  update rule;
    
                 
                  Test.startTest(); 
                       //now create account :-
                       Account a = new Account(Name='shuld be test',AnnualRevenue=500.0,Industry='Agriculture',Type='Customer');
                       insert a;                        
                  Test.stopTest();
              }
         }  
         
         
        static testmethod void testRuleExecutionFalse(){
              WorkflowRule__c rule=setupRules();
              rule.filter_logic__c='AND';
              update rule;
              
              TestHelper.createData();
              
              //now create account :-
              Account a = new Account(Name='shuld be test',AnnualRevenue=500.0,Industry='Mining');
              
              //Create Flex Note
                                    
              FlexNote__c f=new FlexNote__c(Order__c=1.0,FlexNote_Question__c=TestHelper.flexNoteQuestList[0].id,Case__c=TestHelper.caseRrd.Id);
              
              Test.startTest();
                  insert a; 
                  
                  insert f;
                  //get flex note
                  f=[Select Id,Name,Case__c,FlexNote_Question__c FROM FlexNote__c WHERE Id=:f.Id];
                  //system.assertEquals('Flex Note TestEE', f.Name);
                  //system.assertEquals('10', f.Order__c);  
                   //get the account:-
                  a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
                  system.assertEquals('shuld be test', a.Name);
                  system.assertEquals(500, a.AnnualRevenue);                              
              Test.stopTest();
      
         }
      
        
         
         //updated SH
        public  static WorkflowRule__c setupRules(){
            
                WorkflowRule__c rule = new WorkflowRule__c(Name = 'Test Test Account',Object_Name__c = 'Account', Status__c='Draft',Evaluation_Rule__c='Record is created or edited',Description__c='Rule 1 Description');
                insert rule; 
               
               List<WorkflowRuleCriteria__c> criteria = new List<WorkflowRuleCriteria__c>();
               WorkflowRuleCriteria__c c1 = new WorkflowRuleCriteria__c(Workflow_Rule__c=rule.id);
               c1.Field_API_Name__c='Industry';
               c1.Field_Type__c='Picklist';
               c1.Operator__c='Equals';
               c1.Value__c='Agriculture';
               c1.criteria_object__c='Account';
               criteria.add(c1);
               
               WorkflowRuleCriteria__c c2 = new WorkflowRuleCriteria__c(Workflow_Rule__c=rule.id);
               c2.Field_API_Name__c='AnnualRevenue';
               c2.Field_Type__c='Currency';
               c2.Operator__c='Greater Than';
               c2.Value__c='1000';
               c2.criteria_object__c='Account';
               criteria.add(c2);
               
               WorkflowRuleCriteria__c c3 = new WorkflowRuleCriteria__c(Workflow_Rule__c=rule.id);
               c3.Field_API_Name__c='CreatedDate';
               c3.Field_Type__c='Date';
               c3.Operator__c='Greater Than';
               c3.Value__c= String.valueof(date.today());
               c3.criteria_object__c='Account';
               criteria.add(c3);
                        
               insert criteria;
               
               //create action
               List<WorkflowRuleAction__c> actions = new List<WorkflowRuleAction__c>();
               
               WorkflowRuleAction__c a1 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='Name',ActionType__c='Update Field',Value__c='Test');
              
               actions.add(a1);
               
               WorkflowRuleAction__c a2 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='AnnualRevenue',ActionType__c='Update Field',Value__c='2000');
               actions.add(a2);
                        
               // By CC
               WorkflowRuleAction__c a3 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='OwnerId',ActionType__c='Update Field',Value__c=userinfo.getUserId(),Notify_User__c = true);
               actions.add(a3);
               
               WorkflowRuleAction__c a4 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                            ActionType__c='Insert Related Object',child_relationship_name__c='contacts');
               actions.add(a4);
               
               WorkflowRuleAction__c a5 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Attachment',
                                                            ActionType__c='Insert Related Object',child_relationship_name__c='attachments');
               actions.add(a5);
              
               WorkflowRuleAction__c a6 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='Phone',ActionType__c='Update Field',Value__c='{!Owner.Phone}');
               actions.add(a6);
               
               WorkflowRuleAction__c a7 = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Account',
                                                            field_name__c='Description',ActionType__c='Update Field',Long_Value__c='Test content');
               actions.add(a7);
              
              
               insert actions;
               
               List<WorkflowValues_for_Insert_Record__c> infos = new List<WorkflowValues_for_Insert_Record__c>();
               
               WorkflowValues_for_Insert_Record__c info = new WorkflowValues_for_Insert_Record__c(Value__c = 'LastName', Workflow_Rule_Action__c = a4.Id, Name = 'LastName');
               
               infos.add(info);
               
               WorkflowValues_for_Insert_Record__c info2 = new WorkflowValues_for_Insert_Record__c(Value__c = 'Name', Workflow_Rule_Action__c = a4.Id, Name = 'FirstName');
               
               infos.add(info2);
               
               WorkflowValues_for_Insert_Record__c info3 = new WorkflowValues_for_Insert_Record__c(Value__c = '12345', Workflow_Rule_Action__c = a5.Id, Name = 'Body');
               
               infos.add(info3);
               
               WorkflowValues_for_Insert_Record__c info4 = new WorkflowValues_for_Insert_Record__c(Value__c = 'testtxt', Workflow_Rule_Action__c = a5.Id, Name = 'Name');
               
               infos.add(info4);
              
               
                          
               insert infos;
               
               rule =[Select Id,  Status__c,Filter_Logic__c FROM WorkflowRule__c WHERE Id=:rule.Id];
               
               rule.Status__c='Active';
               rule.Evaluation_Rule__c='Record is created or edited and did not previously meet the rule criteria';
               rule.Filter_Logic__c='OR';
               update rule;

               return rule;
         }
         
         
  
    static testmethod void testDoMerge(){
       WorkflowRule__c rule = setupRules();
       
   
       WorkflowRuleAction__c action = new WorkflowRuleAction__c(Workflow_Rule__c=rule.id,action_object__c='Contact',
                                                    ActionType__c='Insert Related Object');
       
       
       insert action;
       
       List<WorkflowValues_for_Insert_Record__c> infos = new List<WorkflowValues_for_Insert_Record__c>();
       
       WorkflowValues_for_Insert_Record__c info = new WorkflowValues_for_Insert_Record__c(Value__c = '{!Name}', Workflow_Rule_Action__c = action.Id, Name = 'LastName');
       
       infos.add(info);
       
       insert infos;

       
       Account a = new Account(Name='should be test',AnnualRevenue=500.0,Industry='Agriculture');
       Test.startTest();
	       insert a;    
	       
       Test.stopTest();
       //get the account:-
	   a=[Select Id,AnnualRevenue,Name,Industry FROM Account WHERE Id=:a.Id];
	   //system.assertEquals('should be test', a.Name.toLowerCase());
	   //system.assertEquals(2000, a.AnnualRevenue);
    }

}