src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>Access_Classification__c</fullName>
        <label>Access Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AnswerValues__c</fullName>
        <label>Answer Values</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Answer_Values__c</fullName>
        <label>Answer Values(delete)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hint_Text__c</fullName>
        <label>Hint Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List__c</fullName>
        <label>List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question(delete)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stop_Date__c</fullName>
        <label>Stop Date</label>
        <type>Date</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FlexNoteQuestionAdminCntrlTest.cls
@IsTest
public class FlexNoteQuestionAdminCntrlTest {
	public static testMethod void testFlexNoteQuestionCntrl(){
       //Use the PageReference Apex class to instantiate a page
       PageReference pageRef = Page.FlexNoteQuestionAdminPge;
       
       //In this case, the Visualforce page named 'FlexNoteQuestionAdminPge' is the starting point of this test method. 
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('isInvokedFrmSRType', 'True');
       
       
       //Instantiate and construct the controller class.   
       FlexNoteQuestionAdminCntrl controller = new FlexNoteQuestionAdminCntrl();
       controller.firstPage();
       //boolean hasNextPge=controller.hasNextPage();
       controller.doCancelFlexNoteQuestion();
       //boolean previousPage=controller.hasPreviousPage();
       
       controller.lastPage();
       
       controller.nextPage();
       controller.previousPage();
       controller.doCreateFlexNoteQuestion();
       
       FlexNoteQuestion__c fNQuestion=new FlexNoteQuestion__c(Object_Name__c='Case',Questions__c='TestQuestion',Answer_Type__c='Text' ,Name='Test');
       insert fnQuestion;
      
       /*FlexNoteQuestion__c tempflexNoteQuestion=[select id,Name,Question__c,Answer_Type__c,Answer_Values__c,Hint_Text__c,List__c,
        Access_Classification__c,Start_Date__c,Stop_Date__c,Object_Name__c from FlexNoteQuestion__c where id=:fNQuestion.id];*/
       string invokedFrmSRType=ApexPages.currentPage().getParameters().get('isInvokedFrmSRType');
       system.assertEquals('True', invokedFrmSRType);
       
       controller.flexNoteQuestionId=fnQuestion.Id;
       controller.flexNoteQuestion=fnQuestion;
       
       controller.doEditFlexNoteQuestion();
       controller.doUpdateFlexNoteQuestion();
       
       controller.flexNoteQuestionId=fnQuestion.Id;
       controller.doDeleteFlexNoteQuestion();
       FlexNoteQuestion__c fNQuestion1=new FlexNoteQuestion__c(Object_Name__c='Case',Questions__c='TestQuestion',Answer_Type__c='Text' ,Name='Test1');
       controller.flexNoteQuestion=fNQuestion1;
       controller.doSaveFlexNoteQuestion();
       
       controller.conditionalRequired=false;
       controller.doConditionalRequiredRender();
       
	}
	
	
	
	public static testMethod void testNegativeValues(){
       //Use the PageReference Apex class to instantiate a page
       PageReference pageRef = Page.FlexNoteQuestionAdminPge;
       
       //In this case, the Visualforce page named 'FlexNoteQuestionAdminPge' is the starting point of this test method. 
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('isInvokedFrmSRType', 'True');
       
       
       //Instantiate and construct the controller class.   
       FlexNoteQuestionAdminCntrl controller = new FlexNoteQuestionAdminCntrl();
       controller.firstPage();
       //boolean hasNextPge=controller.hasNextPage();
       controller.doCancelFlexNoteQuestion();
       //boolean previousPage=controller.hasPreviousPage();
       
       controller.lastPage();
       
       controller.nextPage();
       controller.previousPage();
       controller.doCreateFlexNoteQuestion();
       
        // creating data we have to move this to testhelper class
       FlexNoteQuestion__c fNQuestion=new FlexNoteQuestion__c(Object_Name__c='',Questions__c='',Answer_Type__c='Picklist', Name='TEST2' ,AnswerValues__c=Null);
       insert fnQuestion;
       
      
       /*FlexNoteQuestion__c tempflexNoteQuestion=[select id,Name,Question__c,Answer_Type__c,Answer_Values__c,Hint_Text__c,List__c,
        Access_Classification__c,Start_Date__c,Stop_Date__c,Object_Name__c from FlexNoteQuestion__c where id=:fNQuestion.id];*/
       
       string invokedFrmSRType=ApexPages.currentPage().getParameters().get('isInvokedFrmSRType');
       
       system.assertEquals('True', invokedFrmSRType);
       
       
       controller.showPopUp=true;
       controller.isEditMode=false;
       controller.doSaveFlexNoteQuestion();
       controller.conditionalRequired=true;
       controller.doConditionalRequiredRender();
       
       controller.isEditMode=true;
       controller.flexNoteQuestionId=fnQuestion.Id;
       controller.doEditFlexNoteQuestion(); 
       controller.doUpdateFlexNoteQuestion();
    
       controller.doDeleteFlexNoteQuestion();
       controller.filterStr='A';
       controller.doSearchByAlphabet();
	}
	
	
}