src/objects/FlexNote__c.object
<CustomObject>
    <description>Stores FlexNotes for a Case Object.</description>
    <label>Flex Note</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Flex Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>FlexNote__c</fullName>
        <description>instead of this field use Question__c</description>
        <label>Flex Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestTypeFlexNote__c.object
<CustomObject>
    <description>Contains all the flex notes that related to a service request type and attributes specific to it.</description>
    <label>Service Request Type Flex Note</label>
    <nameField>
        <displayFormat>SRFN-{0000}</displayFormat>
        <label>Service Request Type FlexNote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Type Flex Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionAnswerWrapper.cls
public class QuestionAnswerWrapper {
  // holds service request and question relation
  public ServiceRequestTypeFlexNote__c relationQuestion{get;set;}
  // Determines whether picklist selected other option
  public boolean isRenderText{get;set;}
  // holds Answer for a question
  public FlexNote__c answer{get;set;}
  // holds question picklist values
  public list<SelectOption> questionPicklistValues{get;set;}
  // holds questions 
  public FlexNoteQuestion__c flexNoteQuestion{get;set;}
  // holds multipicklist values 
  public list<QuestionMultiPickListWrapper>questionMultiPicklistValueList{get;set;}
        
  public QuestionAnswerWrapper(FlexNoteQuestion__c flexNoteQuestion,ServiceRequestTypeFlexNote__c relationQuestion){
    this.flexNoteQuestion=flexNoteQuestion;
    this.relationQuestion=relationQuestion;
    this.answer=new FlexNote__c ();
    this.questionPicklistValues=new list<SelectOption>();
    this.isRenderText=false;
    // added
    this.questionMultiPicklistValueList=new list<QuestionMultiPickListWrapper>();
  }   
}