src/objects/Flex_Note_History__c.object
<CustomObject>
    <fields>
        <fullName>CodeDescriptionSourcePart1__c</fullName>
        <label>CodeDescriptionSourcePart1</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CodeDescriptionSourcePart2__c</fullName>
        <label>CodeDescriptionSourcePart2</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Request_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request History</label>
        <referenceTo>Service_Request_History__c</referenceTo>
        <relationshipLabel>Flex Note Histories</relationshipLabel>
        <relationshipName>Flex_Note_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flex Note History</label>
    <nameField>
        <label>Flex Note History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flex Note Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FlexNoteQuestion__c.object
<CustomObject>
    <description>Contains Flex Note Questions and attributes.</description>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Question</label>
        <length>4800</length>
        <type>LongTextArea</type>
    </fields>
    <label>FlexNote Question</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FlexNote Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request_History__c.object
<CustomObject>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>Case Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Request History</label>
    <nameField>
        <label>Service Request History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batchClassFlexNoteHistoryTest.cls
@isTest(seealldata=true)
private class batchClassFlexNoteHistoryTest {
     static testMethod void start() {
         
         batchClassFlexNoteHistory bc=new batchClassFlexNoteHistory ();
         Database.BatchableContext BatchCont;
         //list<case> cas=[Select Id,origin FROM case WHERE origin='311-App' limit 10]; 
         Case c1=new Case(subject='testaroo');
         insert c1;
         Case c2=new Case(subject='testaroo');
         insert c2;
         Case c3=new Case(subject='testaroo');
         insert c3;
         Case c4=new Case(subject='testaroo');
         insert c4;
         
         Service_Request_History__c SRH=new Service_Request_History__c();
         SRH.CaseNumber__c=c1.id;
         insert SRH;
         
         Service_Request_History__c SRH1=new Service_Request_History__c();
         SRH1.CaseNumber__c=c2.id;
         insert SRH1;
         
         Service_Request_History__c SRH2=new Service_Request_History__c();
         SRH2.CaseNumber__c=c3.id;
         insert SRH2;
         
         Service_Request_History__c SRH3=new Service_Request_History__c();
         SRH3.CaseNumber__c=c4.id;
         insert SRH3;

         
         //list<FlexNoteQuestion> lsFNQ=[Select Id,name FROM FlexNoteQuestion WHERE Questions__c='SCHEDULED BULK COLLECTION DATE (cannot be changed)' limit 10];
         FlexNoteQuestion__c FNQ=new FlexNoteQuestion__c();
         FNQ.Questions__c='NEXT BULK SCHEDULE COLLECTION DATE';
         FNQ.Object_Name__c='case';
         FNQ.Name='aaaa';
         FNQ.Answer_Type__c='text';
         insert FNQ;
         
         list<Flex_Note_History__c> ls=new list<Flex_Note_History__c>();
         Flex_Note_History__c FNH=new Flex_Note_History__c();
         FNH.Name='xxxx';
         FNH.Service_Request_History__c=SRH.id;
         FNH.CodeDescriptionSourcePart1__c='FURNI001,HOUSAPP';
         FNH.CodeDescriptionSourcePart2__c='Furniture,Householdapplieances';
         insert FNH;
         ls.add(FNH);
         
         Flex_Note_History__c FNH1=new Flex_Note_History__c();
         FNH1.Name='yy';
         FNH1.Service_Request_History__c=SRH1.id;
         insert FNH1;
         ls.add(FNH1);
         
         Flex_Note_History__c FNH2=new Flex_Note_History__c();
         FNH2.Name='bb';
         FNH2.Service_Request_History__c=SRH2.id;
         FNH2.CodeDescriptionSourcePart1__c='gggg';
         insert FNH2;
         ls.add(FNH2);
         
         Flex_Note_History__c FNH3=new Flex_Note_History__c();
         FNH3.Name='bb';
         FNH3.Service_Request_History__c=SRH3.id;
         FNH3.CodeDescriptionSourcePart2__c='gggg';
         insert FNH3;
         ls.add(FNH3);         

         Flex_Note_History__c FNH4=new Flex_Note_History__c();
         FNH4.Name='awaaw';
         FNH4.Service_Request_History__c=SRH3.id;
         FNH4.CodeDescriptionSourcePart1__c='CODE1,';
         FNH4.CodeDescriptionSourcePart2__c='value1,';
         insert FNH4;
         ls.add(FNH4);         
         
         bc.start(BatchCont);
         bc.execute(BatchCont,ls);
         bc.finish(BatchCont);

         bc.SetAlternateQuery('invalid string');
     }    
}