src/objects/Jurisdiction__c.object
<CustomObject>
    <description>Stores Agency and Department Information of DC Government.</description>
    <label>Agency Dept Code</label>
    <nameField>
        <label>Agency Dept Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Dept Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Open311ApiKeyConfig__c.object
<CustomObject>
    <fields>
        <fullName>ApiKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Api Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Available_SR_Types_For_GET__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <description>The Service Request Types that the specified API key is able to query.</description>
        <label>Available SR Types For GET</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Available_SR_Types_For_POST__c</fullName>
        <label>Available SR Types For POST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Available_SR_Types_For_PUT__c</fullName>
        <label>Available SR Types For PUT</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lock_Activities__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Lock Activities to be returned through GET Service calls for Private API users</inlineHelpText>
        <label>Lock Activities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock_FlexNotes__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Lock Flexnotes to be returned through GET Service calls for Private API users</inlineHelpText>
        <label>Lock FlexNotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box to indicate a Class 2 or Integration Partner status (Cityworks, Trakster, etc) and access level.  Public Open311 submission only (POST) access is granted when unchecked.</description>
        <label>Private</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of requests allocated to the API Key used.</description>
        <label>30 Day Usage Limit Allocation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Reset_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the the usage limit will be reset.</description>
        <inlineHelpText>Set this to the date you wish to have the api key&apos;s usage be reset. The application will automatically register the next iteration 30 days from the date specified when a call is made on the reset date.</inlineHelpText>
        <label>Last Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Limit_Used__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of usage limit that has been used already.</description>
        <label>30 Day Usage Limit Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isCommentsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will describe if comments are required when a Status of a service request has changed.</description>
        <inlineHelpText>Enable this field if you wish to force case closure comments when setting a cases status.</inlineHelpText>
        <label>Are Comments Required for Status Changes</label>
        <type>Checkbox</type>
    </fields>
    <label>Open 311 Api Key Config</label>
    <nameField>
        <label>Agency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open 311 Api Key Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APIValidations.cls
public with sharing class APIValidations {

  /*
    This class will contain all the validations that needs to be applied
    ---- Add all the custom validations here ---
   */


  public static Boolean isValidJuridiction(String jId) {
    //List<Jurisdiction__c> juri = [select id from Jurisdiction__c where Name=:jId];

    string validJurisdiction = 'dc.gov';
    if (jId.equalsIgnoreCase(validJurisdiction) || String.IsBlank(jId)) 
     	return true;
    else
    	return false;
  }

  public static APIKeyResponse validateKey(String key) {

    List<Open311ApiKeyConfig__c> keyConfig = [Select Id, Name, ApiKey__c, Available_SR_Types_For_GET__c, Available_SR_Types_For_POST__c, Available_SR_Types_For_PUT__c, isCommentsRequired__c, Private__c, Lock_FlexNotes__c, Lock_Activities__c, Usage_Limit_Allocation__c, Usage_Limit_Used__c, Usage_Limit_Reset_Date__c FROM Open311ApiKeyConfig__c WHERE ApiKey__c = :key];

    Open311ApiKeyConfig__c validKey;

    if (keyConfig.size() > 0) {
      for (Open311ApiKeyConfig__c k : keyConfig) {
        if (key.equals(k.ApiKey__c)) {
          validKey = k;
          break;
        }
      }
    }

    APIKeyResponse response = new APIKeyResponse();
    response.isValid = false;
    response.apiKey = key;
    if (keyConfig.size() > 0 && validKey != null) {
      response.isValid = true;
      response.name = keyConfig[0].Name;
      response.isPublic = !keyConfig[0].Private__c;
      response.isPrivate = keyConfig[0].Private__c;
      response.flexNotesLocked = keyConfig[0].Lock_FlexNotes__c;
      response.activitiesLocked = keyConfig[0].Lock_Activities__c;
      response.isCommentsRequired = keyConfig[0].isCommentsRequired__c;
      response.usageLimit = keyConfig[0].Usage_Limit_Allocation__c;
      response.usageLimitUsed = keyConfig[0].Usage_Limit_Used__c;
      response.usageLimitResetDate = keyConfig[0].Usage_Limit_Reset_Date__c;
      APIValidations.setupAvailableSRTypes(keyConfig[0].Available_SR_Types_For_GET__c, response.availableSRTypesToQueryForGET);
      APIValidations.setupAvailableSRTypes(keyConfig[0].Available_SR_Types_For_POST__c, response.availableSRTypesToQueryForPOST);
      APIValidations.setupAvailableSRTypes(keyConfig[0].Available_SR_Types_For_PUT__c, response.availableSRTypesToQueryForPUT);
    }
    return response;
  }
    
  public static void setupAvailableSRTypes(String availableTypesStr, Set<String> querySet) {  
    if (String.isNotBlank(availableTypesStr)) {
      // If the field is a CSV of types.
      if (availableTypesStr.contains(',')) {
        List<String> allowedTypesToQueryList = availableTypesStr.split(',');
        // Loop through the available types to create an allowed mapping.
        for (String srType : allowedTypesToQueryList) {
          querySet.add(srType);
        }
      } else {
        // If only one type exists.
        querySet.add(availableTypesStr);
      }
    }    
  }

  public class APIKeyResponse {
    public Boolean isValid { get; set; }
    public Boolean isPublic { get; set; }
    public Boolean isPrivate { get; set; }
    public Boolean flexNotesLocked { get; set; }
    public Boolean activitiesLocked { get; set; }
    public String apiKey { get; set; }
    public String name { get; set; }
    public Boolean isCommentsRequired { get; set; }
    public Decimal usageLimit { get; set; }
    public Decimal usageLimitUsed { get; set; }
    public Date usageLimitResetDate { get; set; }
    public Set<String> availableSRTypesToQueryForGET { get; set; }
    public Set<String> availableSRTypesToQueryForPOST { get; set; }
    public Set<String> availableSRTypesToQueryForPUT { get; set; }
    public String httpMethod { get; set; }

    public APIKeyResponse() {
      isValid = false;
      isPublic = false;
      isPrivate = false;
      flexNotesLocked = false;
      activitiesLocked = false;
      isCommentsRequired = false;
      usageLimit = 0;
      usageLimitUsed = 0;
      availableSRTypesToQueryForGET = new Set<String>();
      availableSRTypesToQueryForPOST = new Set<String>();
      availableSRTypesToQueryForPUT = new Set<String>();
      httpMethod = '';
    }

    public Set<String> getSRTypesToQueryForHttpMethod(String httpMethod) {
      if (httpMethod.equalsIgnoreCase('get')) {
        return availableSRTypesToQueryForGET;
      } else if (httpMethod.equalsIgnoreCase('post')) {
        return availableSRTypesToQueryForPOST;
      } else if (httpMethod.equalsIgnoreCase('put')) {
        return availableSRTypesToQueryForPUT;
      }
      return new Set<String>();
    }
  }


}