src/objects/Open311ApiKeyConfig__c.object
<CustomObject>
    <fields>
        <fullName>Available_SR_Types_For_GET__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <description>The Service Request Types that the specified API key is able to query.</description>
        <label>Available SR Types For GET</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Available_SR_Types_For_POST__c</fullName>
        <label>Available SR Types For POST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Available_SR_Types_For_PUT__c</fullName>
        <label>Available SR Types For PUT</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Open 311 Api Key Config</label>
    <nameField>
        <label>Agency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open 311 Api Key Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Allow_Citizen_Web_Intake__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this SR Type will be available for use on the Citizen Portal.</description>
        <label>Allow Citizen Web Intake</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Open311_SecurityDetailsExtensionTest.cls
@isTest
public class Open311_SecurityDetailsExtensionTest {
  
  public static testMethod void testOpen311_SecurityDetailsExtension() { 
    TestHelper.createData();

    List<Open311ApiKeyConfig__c> config = [Select Id, Available_SR_Types_For_GET__c, Available_SR_Types_For_PUT__c, Available_SR_Types_For_POST__c From Open311ApiKeyConfig__c Limit 1];

    if (config != null && config.size() == 1) {
      Open311_SecurityDetailsExtension ext = new Open311_SecurityDetailsExtension(new ApexPages.StandardController(config.get(0))); 
      System.assertEquals(0, ext.SRTypeOptionsByHttpMethodMap.get('get').get('selectedTypes').options.size());

      config.get(0).Available_SR_Types_For_GET__c = 'DMV19,';
      upsert config;

      List<ServiceRequestType__c> typeList = [Select Id, Allow_Citizen_Web_Intake__c From ServiceRequestType__c Where Name = 'DMV19'];

      if (typeList.size() > 0) {
        typeList.get(0).Allow_Citizen_Web_Intake__c = true;
        update typeList;

        ext = new Open311_SecurityDetailsExtension(new ApexPages.StandardController(config.get(0))); 
        ext.requestedHttpType = 'get';
        ext.picklistChanged();
      }
    }
  }
}