src/objects/ServiceRequestType__c.object
<CustomObject>
    <description>Contains Service Request Types and attributes.</description>
    <fields>
        <fullName>Object__c</fullName>
        <description>Required field - will always be set to Case.</description>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request Type</label>
    <nameField>
        <label>Service Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HelperPaginationClsTest.cls
@isTest
public class HelperPaginationClsTest {
  
  public static testMethod void testPagination(){
    string queryStr='select id,name,Object__c,Service_Name__c from ServiceRequestType__c ORDER BY Service_Name__c';
    string objectName='ServiceRequestType__c';
    integer noOfRows=10;
    HelperPaginationCls hp=new HelperPaginationCls(queryStr,objectName,noOfRows);
    
    list<sObject>recordList=hp.getRecords();
    integer currentPageNo=hp.getCurrentPage();
    
    integer totalSize=hp.getTotalPages();
    
    list<sObject>firstPageList=hp.getFirstPage();
     
    hp.getQueryString();
    integer pageSizeNo=hp.getPageSize();
    
    boolean hasNextPage=hp.hasNextPage();
    
    boolean hasPreviousPage=hp.hasPreviousPage();
    
    //boolean hasLastPage=hp.getLastPage(); 
    
    list<sObject>lastPageList=hp.getLastPage();
    
    list<sObject>nextPageList=hp.nextPage();
    
    list<sObject>previousPageList=hp.previousPage();
  }
  /*
  public static testMethod Void testNegativeValuesInPagination(){
    string queryStr='select id,name,Object__c,Service_Name__c from ServiceRequestType__c ORDER BY Service_Name__c';
    string objectName='ServiceRequestType__c';
    integer noOfRows=10;
    HelperPaginationCls hp=new HelperPaginationCls(queryStr,objectName,noOfRows);
  }*/
}